const fs = require('fs');
const path = require('path');

const targetPath = path.resolve(__dirname, 'src/modules/library/data/heritage_curation/yajurveda_curated.json');

const yajurvedaData = {
  vedaId: "yajurveda",
  vedaName: "यजुर्वेद (Yajurveda)",
  shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना एवं कृष्ण यजुर्वेद तैत्तिरीय शाखा",
  source: "Government of India Vedic Heritage Portal (vedicheritage.gov.in)",
  description: "Authentic curated Yajurveda Suktas, Adhyayas, and Mantras sourced from the Vedic Heritage Portal (vedicheritage.gov.in), featuring Shukla Yajurveda Vajasaneyi Madhyandina Samhita (Adhyayas 1, 16, 22, 34, 36, 40) and Krishna Yajurveda Taittiriya Samhita & Shikshavalli.",
  nodes: [
    {
      id: "shukla-yajurveda",
      slug: "shukla-yajurveda",
      vedaId: "yajurveda",
      parentId: null,
      nodeType: "SHAKHA",
      name: "A. शुक्ल यजुर्वेद (Shukla Yajurveda)",
      enName: "Shukla Yajurveda (Vajasaneyi)",
      desc: "वाजसनेयि परंपरा — याज्ञवल्क्य ऋषि द्वारा सूर्य देव से प्राप्त विशुद्ध मंत्र भाग। इसमें माध्यन्दिना एवं काण्व शाखाएँ प्रमुख हैं।",
      stats: "४० अध्याय • १९७५ मन्त्र",
      priest: "अध्वर्यु (Adhvaryu)",
      badge: "मुख्य परंपरा",
      imageKey: "card-yajurveda.jpg",
      mantraId: "yj-1-1",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "madhyandina-shakha",
      slug: "madhyandina-shakha",
      vedaId: "yajurveda",
      parentId: "shukla-yajurveda",
      nodeType: "SHAKHA",
      name: "1. माध्यन्दिना शाखा (Madhyandina)",
      enName: "Madhyandina Shakha",
      desc: "उत्तर व मध्य भारत में सर्वाधिक प्रचलित वाजसनेयि संहिता शाखा।",
      stats: "४० अध्याय • १९७५ मन्त्र",
      badge: "शाखा",
      imageKey: "card-madhyandina-shakha.jpg",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "vajasaneyi-samhita",
      slug: "vajasaneyi-samhita",
      vedaId: "yajurveda",
      parentId: "madhyandina-shakha",
      nodeType: "SAMHITA",
      name: "क. वाजसनेयि संहिता (मूल मन्त्र भाग)",
      enName: "Vajasaneyi Samhita",
      desc: "४० अध्याय, ३०३ अनुवाक, १९७५ कण्डिकाएँ — दर्शपूर्णमास, शतरुद्रीय, शिवसंकल्प, ईशावास्योपनिषद।",
      stats: "४० अध्याय • १९७५ मन्त्र",
      badge: "संहिता ग्रंथ",
      imageKey: "card-samhita.jpg",
      mantraId: "yj-1-1",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "yj-adhyaya-1",
      slug: "yj-adhyaya-1",
      vedaId: "yajurveda",
      parentId: "vajasaneyi-samhita",
      nodeType: "ADHYAYA",
      name: "१. दर्शपूर्णमास याग (अध्याय १ - इषे त्वोर्जे त्वा...)",
      enName: "Adhyaya 1 (Darshapurnamasa Yajna)",
      desc: "यजुर्वेद का प्रथम अध्याय। पलाश शाखा छेदन, वत्स अपाकरण, यज्ञीय पवित्रता एवं अन्न-ऊर्जा संवर्धन।",
      stats: "३१ मन्त्र • अध्याय १",
      badge: "अध्याय",
      imageKey: "card-yagya.jpg",
      mantraId: "yj-1-1",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "yj-adhyaya-16",
      slug: "yj-adhyaya-16",
      vedaId: "yajurveda",
      parentId: "vajasaneyi-samhita",
      nodeType: "ADHYAYA",
      name: "२. शतरुद्रीय / रुद्राध्याय (अध्याय १६ - नमस्ते रुद्र मन्यव...)",
      enName: "Adhyaya 16 (Shri Rudram / Namakam)",
      desc: "रुद्राष्टाध्यायी का पंचम अध्याय (नमकम्)। भगवान शिव के सर्वव्यापक, कल्याणकारी एवं संहारक स्वरूप की ६६ ऋचाओं में वन्दना।",
      stats: "६६ मन्त्र • अध्याय १६",
      badge: "अध्याय",
      imageKey: "card-rudra.jpg",
      mantraId: "yj-16-1",
      orderIndex: 2,
      status: "ACTIVE"
    },
    {
      id: "yj-adhyaya-22",
      slug: "yj-adhyaya-22",
      vedaId: "yajurveda",
      parentId: "vajasaneyi-samhita",
      nodeType: "ADHYAYA",
      name: "३. राष्ट्र समृद्धि प्रार्थना (अध्याय २२ - आ ब्रह्मन् ब्राह्मणो...)",
      enName: "Adhyaya 22 (Rashtra Samriddhi & Ashvamedha)",
      desc: "राष्ट्र की सर्वांगीण समृद्धि, शूरवीर योद्धा, दुग्धवती गौएं, मेधावी युवा और समयानुसार वर्षा की दिव्य वैदिक प्रार्थना।",
      stats: "३४ मन्त्र • अध्याय २२",
      badge: "अध्याय",
      imageKey: "card-rashtra.jpg",
      mantraId: "yj-22-22",
      orderIndex: 3,
      status: "ACTIVE"
    },
    {
      id: "yj-adhyaya-34",
      slug: "yj-adhyaya-34",
      vedaId: "yajurveda",
      parentId: "vajasaneyi-samhita",
      nodeType: "ADHYAYA",
      name: "४. शिवसंकल्प सूक्त (अध्याय ३४ - तन्मे मनः शिवसंकल्पमस्तु)",
      enName: "Adhyaya 34 (Shiva Sankalpa Sukta)",
      desc: "वैदिक मनोविज्ञान का शिखर। मन की असीम शक्ति, ज्योतिर्मय स्वरूप और कल्याणकारी संकल्प की ६ अमर ऋचाएँ।",
      stats: "६ मन्त्र • अध्याय ३४",
      badge: "सूक्त / अध्याय",
      imageKey: "card-shivasankalpa.jpg",
      mantraId: "yj-34-1",
      orderIndex: 4,
      status: "ACTIVE"
    },
    {
      id: "yj-adhyaya-36",
      slug: "yj-adhyaya-36",
      vedaId: "yajurveda",
      parentId: "vajasaneyi-samhita",
      nodeType: "ADHYAYA",
      name: "५. विश्व शान्ति पाठ (अध्याय ३६ - द्यौः शान्तिरन्तरिक्षं...)",
      enName: "Adhyaya 36 (Vishva Shanti Patha)",
      desc: "ब्रह्माण्डीय पर्यावरण और चराचर जगत में शान्ति, सन्तुलन और सामंजस्य का सार्वभौमिक वैदिक महामन्त्र।",
      stats: "२४ मन्त्र • अध्याय ३६",
      badge: "अध्याय",
      imageKey: "card-shanti.jpg",
      mantraId: "yj-36-17",
      orderIndex: 5,
      status: "ACTIVE"
    },
    {
      id: "yj-adhyaya-40",
      slug: "yj-adhyaya-40",
      vedaId: "yajurveda",
      parentId: "vajasaneyi-samhita",
      nodeType: "UPANISHAD",
      name: "६. ईशावास्योपनिषद (अध्याय ४० - ईशा वास्यमिदं सर्वम्...)",
      enName: "Adhyaya 40 (Ishavasya Upanishad)",
      desc: "यजुर्वेद का अंतिम ४०वाँ अध्याय। उपनिषद् साहित्य का मुकुटमणि — त्यागपूर्वक भोग, कर्मयोग एवं आत्म-साक्षात्कार का अद्वैत दर्शन।",
      stats: "१८ मन्त्र • अध्याय ४०",
      badge: "उपनिषद",
      imageKey: "card-ishavasya.jpg",
      mantraId: "yj-40-1",
      orderIndex: 6,
      status: "ACTIVE"
    },
    {
      id: "krishna-yajurveda",
      slug: "krishna-yajurveda",
      vedaId: "yajurveda",
      parentId: null,
      nodeType: "SHAKHA",
      name: "B. कृष्ण यजुर्वेद (Krishna Yajurveda)",
      enName: "Krishna Yajurveda (Charaka)",
      desc: "चरक परंपरा — मन्त्र एवं ब्राह्मण भाग का समन्वित संकलन। तैत्तिरीय, मैत्रायणी, काठक एवं कपिष्ठल शाखाएँ।",
      stats: "४ मुख्य शाखाएँ",
      priest: "अध्वर्यु (Adhvaryu)",
      badge: "मुख्य परंपरा",
      imageKey: "card-yajurveda.jpg",
      mantraId: "yj-kr-1-1",
      orderIndex: 2,
      status: "ACTIVE"
    },
    {
      id: "taittiriya-shakha",
      slug: "taittiriya-shakha",
      vedaId: "yajurveda",
      parentId: "krishna-yajurveda",
      nodeType: "SHAKHA",
      name: "1. तैत्तिरीय शाखा (Taittiriya Shakha)",
      enName: "Taittiriya Shakha",
      desc: "दक्षिण भारत में सर्वाधिक प्रचलित एवं संरक्षित कृष्ण यजुर्वेद की मुख्य शाखा।",
      stats: "७ काण्ड • ४४ प्रपाठक",
      badge: "शाखा",
      imageKey: "card-taittiriya-shakha.jpg",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "taittiriya-samhita",
      slug: "taittiriya-samhita",
      vedaId: "yajurveda",
      parentId: "taittiriya-shakha",
      nodeType: "SAMHITA",
      name: "क. तैत्तिरीय संहिता",
      enName: "Taittiriya Samhita",
      desc: "७ काण्ड, ४४ प्रपाठक, ६५१ अनुवाक, २१९८ कण्डिकाएँ। दर्शपूर्णमास, राजसूय, वाजपेय एवं सोमयाग विधान।",
      stats: "७ काण्ड • ४४ प्रपाठक",
      badge: "संहिता",
      imageKey: "card-samhita.jpg",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "taittiriya-upanishad",
      slug: "taittiriya-upanishad",
      vedaId: "yajurveda",
      parentId: "taittiriya-shakha",
      nodeType: "UPANISHAD",
      name: "ख. तैत्तिरीय उपनिषद् (शिक्षावल्ली)",
      enName: "Taittiriya Upanishad (Shikshavalli)",
      desc: "शिक्षावल्ली, ब्रह्मानन्दवल्ली एवं भृगुवल्ली। 'सत्यं वद धर्मं चर' और 'मातृदेवो भव पितृदेवो भव' के अमर उपदेश।",
      stats: "३ वल्लियाँ • शिक्षावल्ली",
      badge: "उपनिषद",
      imageKey: "card-upanishad.jpg",
      mantraId: "yj-kr-1-1",
      orderIndex: 2,
      status: "ACTIVE"
    }
  ],
  mantras: [
    {
      id: "yj-1-1",
      slug: "yj-1-1",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-1",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (दर्शपूर्णमास याग)",
      sectionRef: "अध्याय १, मन्त्र १",
      mantraNumber: "१.१",
      rishi: "परमेष्ठी प्रजापति",
      devata: "यज्ञ एवं सविता",
      chhanda: "यजुः (गद्यात्मक वैदिक छन्द)",
      svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
      sanskrit: "ॐ इ॒षे त्वो॒र्जे त्वा॑ वा॒यव॑ स्थ दे॒वो वः॑ सवि॒ता प्रार्प॑यतु॒ श्रेष्ठ॑तमाय॒ कर्म॑णे॥१॥",
      transliteration: "oṃ iṣe tvorje tvā vāyava stha devo vaḥ savitā prārpayatu śreṣṭhatamāya karmaṇe || 1 ||",
      hindiTranslation: "हे पलाश शाखा! हम तुम्हें अन्न की समृद्धि के लिए ग्रहण करते हैं, और रस/ऊर्जा की वृद्धि के लिए ग्रहण करते हैं। हे बछड़ों! तुम वायु के समान वेगवान और पवित्र बनो। दिव्य सविता देव तुम्हें सर्वोत्तम यज्ञ-कर्म के लिए प्रेरित करें।",
      englishTranslation: "For nourishment and vigorous energy we accept thee; O calves, be swift and pure as the sacred wind. May the divine inspirer Savitr impel you all unto the highest, most auspicious action.",
      hinglishTranslation: "Anna aur urja ki vriddhi ke liye hum tumhe grahan karte hain. Hey vatsa, tum vayu ke saman tejaswi bano. Savita Dev tumhe shreshthatam karma ke liye prerit karein.",
      padapatha: [
        { word: "इ॒षे", meaning: "अन्न व पुष्टि के लिए" },
        { word: "त्वा॑", meaning: "तुझे (पलाश शाखा को)" },
        { word: "ऊ॒र्जे", meaning: "रस एवं पराक्रम के लिए" },
        { word: "त्वा॑", meaning: "तुझे" },
        { word: "वा॒यवः॑", meaning: "वायु के समान वेगवान" },
        { word: "स्थ॒", meaning: "होओ" },
        { word: "दे॒वः", meaning: "प्रकाशमान" },
        { word: "स॒वि॒ता", meaning: "सृष्टिकर्ता सविता परमात्मा" },
        { word: "प्र", meaning: "प्रकर्ष रूप से" },
        { word: "अ॒र्प॒य॒तु॒", meaning: "प्रेरित करे" },
        { word: "श्रेष्ठ॑तमाय", meaning: "सर्वोत्तम" },
        { word: "कर्म॑णे", meaning: "पवित्र यज्ञ कर्म के लिए" }
      ],
      shastricContext: "यजुर्वेद का प्रथम महामन्त्र। यह मन्त्र मानव जीवन में कर्मयोग का सूत्रपात करता है और यज्ञ को संसार का 'श्रेष्ठतम कर्म' (सर्वोच्च कर्तव्य) घोषित करता है।",
      orderIndex: 1,
      status: "ACTIVE"
    },
    {
      id: "yj-16-1",
      slug: "yj-16-1",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-16",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (शतरुद्रीय - श्रीरुद्रम्)",
      sectionRef: "अध्याय १६, मन्त्र १",
      mantraNumber: "१६.१",
      rishi: "परमेष्ठी प्रजापति",
      devata: "रुद्र (Shiva - Rudra)",
      chhanda: "पंक्ति (४० वर्ण)",
      svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
      sanskrit: "ॐ नम॑स्ते रुद्र म॒न्यव॑ उ॒तो त॒ इष॑वे॒ नमः॑।\nबा॒हुभ्या॑मु॒त ते॒ नमः॑॥१॥",
      transliteration: "oṃ namas te rudra manyava uto ta iṣave namaḥ |\nbāhubhyām uta te namaḥ || 1 ||",
      hindiTranslation: "हे दुःखों के नाशक और न्यायकारी भगवान रुद्र! आपके मन्यु (दुष्टों के प्रति सात्त्विक क्रोध) को हमारा नमस्कार है। आपके तीक्ष्ण बाण को नमस्कार है, और आपकी दोनों पराक्रमी भुजाओं को हमारा सादर प्रणाम है।",
      englishTranslation: "O Rudra, homage unto your righteous wrath, and homage unto your piercing arrow. Homage be unto both of your mighty, protective arms.",
      hinglishTranslation: "Hey dukh-vinashak Bhagwan Rudra, aapke satvik krodh ko pranam, aapke baan ko pranam aur aapki dono shaktishali bhujaon ko hamara barambar pranam.",
      padapatha: [
        { word: "नमः॑", meaning: "सादर नमस्कार" },
        { word: "ते॒", meaning: "आपके" },
        { word: "रु॒द्र॒", meaning: "हे पापनाशक रुद्र" },
        { word: "म॒न्यवे॑", meaning: "धार्मिक क्रोध को" },
        { word: "उ॒तो", meaning: "और भी" },
        { word: "ते॒", meaning: "आपके" },
        { word: "इष॑वे", meaning: "दिव्य बाण को" },
        { word: "नमः॑", meaning: "प्रणाम" },
        { word: "बा॒हुभ्या॑म्", meaning: "दोनों भुजाओं को" },
        { word: "उ॒त", meaning: "और" },
        { word: "ते॒", meaning: "आपके" },
        { word: "नमः॑", meaning: "नमस्कार" }
      ],
      shastricContext: "रुद्राष्टाध्यायी (शतरुद्रीय / नमकम्) का प्रथम और मूल मन्त्र। समस्त रुद्राभिषेक एवं शिवोपासना का यह प्रामाणिक वैदिक उद्गम है।",
      orderIndex: 2,
      status: "ACTIVE"
    },
    {
      id: "yj-16-2",
      slug: "yj-16-2",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-16",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (शतरुद्रीय - श्रीरुद्रम्)",
      sectionRef: "अध्याय १६, मन्त्र २",
      mantraNumber: "१६.२",
      rishi: "परमेष्ठी प्रजापति",
      devata: "रुद्र (Shiva - Shanta Swarupa)",
      chhanda: "अनुष्टुप्",
      svara: "सस्वर वैदिक पाठ",
      sanskrit: "या ते॑ रुद्र शि॒वा त॒नूरघो॒राऽपा॑पकाशिनी।\nतया॑ नस्त॒नुवा॒ शंत॑मया गि॑रिश॒न्ताभि॑ चाकशीहि॥२॥",
      transliteration: "yā te rudra śivā tanūr aghorā'pāpakāśinī |\ntayā nas tanuvā śantamayā giriśantābhi cākaśīhi || 2 ||",
      hindiTranslation: "हे कैलासवासी मंगलमय रुद्र! आपकी जो परम शान्त, अघोर (अक्रोध) और पापों का नाश करने वाली शिव (कल्याणमयी) मूर्ति है, उस अतिशय सुखदायिनी कान्ति से हमारी ओर कृपापूर्वक दृष्टिपात कीजिए।",
      englishTranslation: "O Rudra who dwelleth on the holy heights, with that auspicious (Shiva), non-terrific, sin-destroying form of Thine, look upon us with Thine most peaceful and blissful grace.",
      hinglishTranslation: "Hey Kailashwasi mangalkari Rudra, aapka jo shant, kalyankari aur papnashak swaroop hai, us param sukhdayi roop se hum par kripa drishti banaye rakhiye.",
      padapatha: [
        { word: "या", meaning: "जो" },
        { word: "ते॒", meaning: "आपकी" },
        { word: "रु॒द्र॒", meaning: "हे रुद्र" },
        { word: "शि॒वा", meaning: "कल्याणकारी" },
        { word: "त॒नूः", meaning: "दिव्य मूर्ति/स्वरूप" },
        { word: "अ॒घो॒रा", meaning: "भयरहित/शान्त" },
        { word: "अपा॑प-काशिनी", meaning: "पुण्य को प्रकाशित करने वाली" },
        { word: "तया॑", meaning: "उस" },
        { word: "नः॑", meaning: "हमको" },
        { word: "त॒नुवा॑", meaning: "स्वरूप से" },
        { word: "शंत॑मया", meaning: "परम सुखदायिनी" },
        { word: "गि॒रि॒-श॒न्त॒", meaning: "पर्वत पर सुख बरसाने वाले" },
        { word: "अ॒भि", meaning: "सम्मुख" },
        { word: "चा॒क॒शी॒हि॒", meaning: "कृपापूर्वक देखिए" }
      ],
      shastricContext: "रुद्र के 'घोर' रूप को 'शिव' (कल्याणमय) रूप में परिवर्तित करने वाली परम स्तुति। श्वेताश्वतरोपनिषद् (३.५) में भी यह मन्त्र उद्धृत है।",
      orderIndex: 3,
      status: "ACTIVE"
    },
    {
      id: "yj-22-22",
      slug: "yj-22-22",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-22",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (राष्ट्र समृद्धि प्रार्थना)",
      sectionRef: "अध्याय २२, मन्त्र २२",
      mantraNumber: "२२.२२",
      rishi: "प्रजापति",
      devata: "राष्ट्र एवं सर्वदेव",
      chhanda: "यजुः महामन्त्र",
      svara: "सस्वर वैदिक पाठ",
      sanskrit: "ॐ आ ब्रह्मन् ब्राह्मणो ब्रह्मवर्चसी जायतामा राष्ट्रे राजन्यः शूर इषव्योऽतिव्याधी महारथो जायतां दोग्ध्री धेनुर्वोढाऽनड्वानाशुः सप्तिः पुरन्धिर्योषा जिष्णू रथेष्ठाः सभेयो युवास्य यजमानस्य वीरो जायतां निकामे-निकामे नः पर्जन्यो वर्षतु फलवत्यो न ओषधयः पच्यन्तां योगक्षेमो नः कल्पताम्॥२२॥",
      transliteration: "oṃ ā brahman brāhmaṇo brahmavarcasī jāyatām ā rāṣṭre rājanyaḥ śūra iṣavyo'tivyādhī mahāratho jāyatāṃ dogdhrī dhenur voḍhā'naḍvān āśuḥ saptiḥ purandhir yoṣā jiṣṇū ratheṣṭhāḥ sabheyo yuvāsya yajamānasya vīro jāyatāṃ nikāme-nikāme naḥ parjanyo varṣatu phalavatyo na oṣadhayaḥ pacyantāṃ yogakṣemo naḥ kalpatām || 22 ||",
      hindiTranslation: "हे परमेश्वर! हमारे राष्ट्र में ज्ञानवान ब्राह्मण ब्रह्मतेज से युक्त हों; क्षत्रिय शूरवीर, अचूक धनुर्धारी, महारथी हों; गौएं प्रचुर दुग्ध देने वाली हों; बैल उत्तम भारवाहक हों; अश्व द्रुतगामी हों; नारियाँ सुशीला एवं गृहलक्ष्मी हों; युवा विजयी, सभ्य और पराक्रमी हों। हमारी आवश्यकता अनुसार समयानुसार मेघ वर्षा करें, वनस्पतियाँ फलों से लदी हों, और हमारा योगक्षेम (अप्राप्त की प्राप्ति और प्राप्त की रक्षा) सुरक्षित रहे।",
      englishTranslation: "O Supreme Lord! In our nation, may spiritual seekers be radiant with divine wisdom; may leaders and warriors be valiant archers and great heroes; may the cows yield plentiful milk; may the oxen bear heavy burdens; may the steeds be swift; may the women be noble and cultured; may the youth be victorious and enlightened assembly members. May the rains descend whenever needed; may our plants ripen with abundant fruit, and may our wellbeing and prosperity (Yogakshema) be eternally sustained.",
      hinglishTranslation: "Hey Ishwar! Hamare rashtra me gyanvan log brahma-tej se yukt hon, yoddha veer hon, gaayein doodh dene wali hon, nariyan shreshtha aur yuva sanskari hon. Samay par varsha ho aur rashtra ka yogakshem surakshit rahe.",
      padapatha: [
        { word: "आ", meaning: "उत्कृष्ट रूप से" },
        { word: "ब्रह्मन्", meaning: "हे ब्रह्म/परमात्मा" },
        { word: "ब्राह्मणः", meaning: "ज्ञानवान साधक" },
        { word: "ब्रह्म-वर्चसी", meaning: "ब्रह्मतेज से युक्त" },
        { word: "जायताम्", meaning: "उत्पन्न हों" },
        { word: "राष्ट्रे", meaning: "राष्ट्र में" },
        { word: "राजन्यः", meaning: "शासक/क्षत्रिय" },
        { word: "शूरः", meaning: "पराक्रमी" },
        { word: "महारथः", meaning: "महारथी" },
        { word: "दोग्ध्री", meaning: "प्रचुर दूध देने वाली" },
        { word: "धेनुः", meaning: "गौएं" },
        { word: "योग-क्षेमः", meaning: "अप्राप्त की प्राप्ति व प्राप्त की रक्षा" },
        { word: "कल्पताम्", meaning: "सिद्ध होवे" }
      ],
      shastricContext: "वैदिक राष्ट्रगीत और राष्ट्र की समग्र सुरक्षा, सम्पन्नता एवं समृद्धि का विश्व-प्रसिद्ध प्रामाणिक मन्त्र।",
      orderIndex: 4,
      status: "ACTIVE"
    },
    {
      id: "yj-34-1",
      slug: "yj-34-1",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-34",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (शिवसंकल्प सूक्त)",
      sectionRef: "अध्याय ३४, मन्त्र १",
      mantraNumber: "३४.१",
      rishi: "शिवसंकल्प",
      devata: "मन (Pure Subconscious Mind)",
      chhanda: "त्रिष्टुप् (४४ वर्ण)",
      svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
      sanskrit: "ॐ यज्जाग्र॑तो दू॒रमुदै॑ति॒ दैवं॒ तदु॑ सु॒प्तस्य॒ तथैवेति॑।\nदू॒रं॒ग॒मं ज्योति॑षां॒ ज्योति॒रेकं॒ तन्मे॒ मनः॑ शि॒वस॑ङ्क॒ल्पम॑स्तु॥१॥",
      transliteration: "oṃ yaj jāgrato dūram udaiti daivaṃ tad u suptasya tathaivaiti |\ndūraṅ-gamaṃ jyotiṣāṃ jyotir ekaṃ tan me manaḥ śiva-saṅkalpam astu || 1 ||",
      hindiTranslation: "जागते हुए मनुष्य का जो दिव्य मन दूर-दूर तक विचरण करता है और सोते हुए भी उसी प्रकार सुदूर चला जाता है; जो समस्त इन्द्रिय-ज्योतियों की एकमात्र मूल ज्योति है—वह मेरा मन सदा कल्याणकारी और पवित्र संकल्पों से युक्त बने।",
      englishTranslation: "That divine mind which wanders far away when awake, and likewise in deep sleep; that far-traveling light of all lights—may that mind of mine be filled with auspicious, noble resolve.",
      hinglishTranslation: "Jaagte hue jo man door-door tak daudta hai aur sote hue bhi waisa hi karta hai; jo sabhi indriyon ki akeli jyoti hai—mera wah man shubh sankalpo wala bane.",
      padapatha: [
        { word: "यत्", meaning: "जो" },
        { word: "जाग्र॑तः", meaning: "जागते हुए का" },
        { word: "दू॒रम्", meaning: "दूर" },
        { word: "उदै॑ति", meaning: "जाता है" },
        { word: "दैव॑म्", meaning: "दिव्य शक्ति युक्त" },
        { word: "तन्मे॑", meaning: "वह मेरा" },
        { word: "मनः॑", meaning: "मन" },
        { word: "शि॒व-स॑ङ्क॒ल्पम्", meaning: "कल्याणकारी संकल्प वाला" },
        { word: "अ॒स्तु॒", meaning: "होवे" }
      ],
      shastricContext: "वैदिक मनोविज्ञान का अमर मन्त्र। मन की दिशा को सदा सकारात्मक और पवित्र रखने की प्रार्थना।",
      orderIndex: 5,
      status: "ACTIVE"
    },
    {
      id: "yj-34-2",
      slug: "yj-34-2",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-34",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (शिवसंकल्प सूक्त)",
      sectionRef: "अध्याय ३४, मन्त्र २",
      mantraNumber: "३४.२",
      rishi: "शिवसंकल्प",
      devata: "मन",
      chhanda: "त्रिष्टुप्",
      svara: "सस्वर वैदिक पाठ",
      sanskrit: "येन॒ कर्म्मा॑ण्य॒पसो॑ मनी॒षिणो॑ य॒ज्ञे कृ॒ण्वन्ति॑ वि॒दथे॑षु॒ धीराः॑।\nयद॑पू॒र्वं य॒क्षम॒न्तः प्र॒जानां॒ तन्मे॒ मनः॑ शि॒वस॑ङ्क॒ल्पम॑स्तु॥२॥",
      transliteration: "yena karmāṇy apaso manīṣiṇo yajñe kṛṇvanti vidatheṣu dhīrāḥ |\nyad apūrvaṃ yakṣam antaḥ prajānāṃ tan me manaḥ śiva-saṅkalpam astu || 2 ||",
      hindiTranslation: "जिस मन की सामर्थ्य से कर्मनिष्ठ ज्ञानी और धैर्यवान मनीषी यज्ञों और विद्वत्-सभाओं में श्रेष्ठ कर्म सम्पन्न करते हैं; जो समस्त प्राणियों के भीतर प्रतिष्ठित एक अपूर्व, पूजनीय दिव्य तत्त्व है—वह मेरा मन सदा कल्याणकारी संकल्पों से युक्त रहे।",
      englishTranslation: "Whereby the wise and diligent performers of righteous deeds accomplish sacred rites in assemblies; that peerless, adorable wondrous power residing within all beings—may that mind of mine be filled with auspicious intent.",
      hinglishTranslation: "Jis man ki shakti se gyani log yagya aur sabhaon me shreshtha kaam karte hain; jo sabhi praniyo ke andar pujya divya tatva hai—mera wah man shubh sankalpo se yukt ho.",
      padapatha: [
        { word: "येन॑", meaning: "जिसके द्वारा" },
        { word: "कर्मा॑णि", meaning: "श्रेष्ठ कर्मों को" },
        { word: "अ॒पसः॑", meaning: "कर्मशील जन" },
        { word: "म॒नी॒षिणः॑", meaning: "बुद्धिमान मनीषी" },
        { word: "य॒ज्ञे", meaning: "यज्ञ में" },
        { word: "कृ॒ण्वन्ति॑", meaning: "करते हैं" },
        { word: "अ॒पू॒र्वम्", meaning: "अद्भुत/अद्वितीय" },
        { word: "य॒क्षम्", meaning: "पूजनीय शक्ति" },
        { word: "शि॒व-स॑ङ्क॒ल्पम्", meaning: "कल्याणकारी संकल्प" }
      ],
      shastricContext: "मानव की कर्म-कुशलता और अंतःकरण की पवित्रता का परस्पर सम्बन्ध निरूपित करता है।",
      orderIndex: 6,
      status: "ACTIVE"
    },
    {
      id: "yj-34-6",
      slug: "yj-34-6",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-34",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (शिवसंकल्प सूक्त)",
      sectionRef: "अध्याय ३४, मन्त्र ६",
      mantraNumber: "३४.६",
      rishi: "शिवसंकल्प",
      devata: "मन",
      chhanda: "त्रिष्टुप्",
      svara: "सस्वर वैदिक पाठ",
      sanskrit: "सु॒षा॒र॒थिरश्वा॑निव॒ यन्म॑नु॒ष्यान्नेनी॑यते॒ऽभीशु॑भिर्वा॒जिन॑ इव।\nहृत्प्र॑ति॒ष्ठं यद॒जिरं॒ जवि॑ष्ठं॒ तन्मे॒ मनः॑ शि॒वस॑ङ्क॒ल्पम॑स्तु॥६॥",
      transliteration: "suṣārathir aśvān iva yan manuṣyān nenīyate'bhīśubhir vājina iva |\nhṛt-pratiṣṭhaṃ yad ajiraṃ javiṣṭhaṃ tan me manaḥ śiva-saṅkalpam astu || 6 ||",
      hindiTranslation: "जैसे एक कुशल सारथी घोड़ों को लगाम के सहारे सही दिशा में ले जाता है, वैसे ही जो मन मनुष्य को सदा संचालित करता है; जो हृदय में प्रतिष्ठित, कभी वृद्ध न होने वाला और तीव्रतम गतिवान है—वह मेरा मन सदा शुभ, कल्याणकारी संकल्पों से युक्त रहे।",
      englishTranslation: "As a skillful charioteer controls and guides swift horses with reins, so does the mind direct human beings; that unaging, swiftest power anchored in the heart—may that mind of mine be filled with noble, auspicious resolve.",
      hinglishTranslation: "Jaise kushal sarathi ghodo ko lagam se sahi raste par le jata hai, waise hi jo man manushya ko chalata hai; jo hriday me sthit aur sabse tez hai—mera wah man shubh sankalpo wala bane.",
      padapatha: [
        { word: "सु॒-सा॒र॒थिः", meaning: "उत्कृष्ट सारथी" },
        { word: "अश्वा॑न्-इव", meaning: "घोड़ों के समान" },
        { word: "यत्", meaning: "जो मन" },
        { word: "म॒नु॒ष्यान्", meaning: "मनुष्यों को" },
        { word: "नेनी॑यते", meaning: "संचालित करता है" },
        { word: "हृत्-प्र॑ति॒ष्ठम्", meaning: "हृदय में स्थित" },
        { word: "अ॒जि॒रम्", meaning: "अजर/सदा नवीन" },
        { word: "जवि॑ष्ठम्", meaning: "अत्यंत तीव्रगामी" }
      ],
      shastricContext: "शिवसंकल्प सूक्त का अंतिम मन्त्र। कठोपनिषद् की 'रथी आत्मा, शरीर रथ, बुद्धि सारथी और मन लगाम' की रूपक कथा का यही मूल स्रोत है।",
      orderIndex: 7,
      status: "ACTIVE"
    },
    {
      id: "yj-36-17",
      slug: "yj-36-17",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-36",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "वाजसनेयि संहिता (विश्व शान्ति पाठ)",
      sectionRef: "अध्याय ३६, मन्त्र १७",
      mantraNumber: "३६.१७",
      rishi: "प्रजापति",
      devata: "विश्वेदेवाः एवं विश्व शान्ति",
      chhanda: "निचृद् भुरिगनुष्टुप्",
      svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
      sanskrit: "ॐ द्यौः शान्ति॑र॒न्तरि॑क्षं॒ शान्तिः॑ पृथि॒वी शान्ति॒रापः॒ शान्ति॒रोष॑धयः॒ शान्तिः॑।\nवन॒स्पत॑यः॒ शान्ति॒र्विश्वे॑ दे॒वाः शान्ति॒र्ब्रह्म॒ शान्तिः॒ सर्वं॒ शान्तिः॒ शान्ति॑रेव॒ शान्तिः॒ सा मा॒ शान्ति॑रेधि॥",
      transliteration: "oṃ dyauḥ śāntir antarikṣaṃ śāntiḥ pṛthivī śāntir āpaḥ śāntir oṣadhayaḥ śāntiḥ |\nvanaspatayaḥ śāntir viśve devāḥ śāntir brahma śāntiḥ sarvaṃ śāntiḥ śāntir eva śāntiḥ sā mā śāntir edhi ||",
      hindiTranslation: "द्युलोक शांत हो, अंतरिक्ष शांत हो, पृथ्वी शांत हो, जल शांत हो, ओषधियाँ शांत हों, वनस्पतियाँ शांत हों, समस्त देवगण शांत हों, परब्रह्म शांत हो, संपूर्ण विश्व शांत हो; शांति ही चारों ओर शांत हो, और वह दिव्य शांति मुझमें भी प्रतिष्ठित हो।",
      englishTranslation: "May peace radiate in the celestial realms, in intermediate space, upon earth, within waters, among medicinal herbs, and in trees. May peace reside in all deities, in Brahman, and in all existence. May absolute peace prevail, and may that peace enter into me.",
      hinglishTranslation: "Aakash, antariksh, prithvi, jal, aushadhi aur ped-paudho me shanti ho. Sabhi devtao aur Brahma me shanti ho. Charo taraf shanti hi shanti ho aur wah shanti mujhe prapt ho.",
      padapatha: [
        { word: "द्यौः", meaning: "द्युलोक" },
        { word: "शान्तिः॑", meaning: "शान्त हो" },
        { word: "अ॒न्तरि॑क्षम्", meaning: "अंतरिक्ष लोक" },
        { word: "शान्तिः॑", meaning: "शान्त हो" },
        { word: "पृ॒थि॒वी", meaning: "धरती माता" },
        { word: "आपः॑", meaning: "जल तत्त्व" },
        { word: "ओष॑धयः", meaning: "औषधियाँ" },
        { word: "वन॒स्पत॑यः", meaning: "वृक्ष" },
        { word: "विश्वे॑", meaning: "समस्त" },
        { word: "दे॒वाः", meaning: "देवगण" },
        { word: "ब्रह्म॑", meaning: "परब्रह्म" },
        { word: "सर्व॑म्", meaning: "समस्त चराचर" }
      ],
      shastricContext: "सनातन वैदिक संस्कृति का सार्वभौमिक शांति पाठ। पर्यावरण, ब्रह्माण्ड और मानव चेतना के मध्य सामंजस्य का परम सूत्र।",
      orderIndex: 8,
      status: "ACTIVE"
    },
    {
      id: "yj-40-1",
      slug: "yj-40-1",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-40",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "ईशावास्योपनिषद् (वाजसनेयि संहिता ४०वां अध्याय)",
      sectionRef: "अध्याय ४०, मन्त्र १",
      mantraNumber: "४०.१",
      rishi: "दध्यङ् आथर्वण",
      devata: "ईश्वर / आत्मतत्त्व",
      chhanda: "अनुष्टुप्",
      svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
      sanskrit: "ॐ ई॒शा वा॒स्य॑मि॒दं सर्वं॒ यत्किञ्च॒ जग॑त्यां॒ जग॑त्।\nतेन॑ त्य॒क्तेन॑ भुञ्जीथा॒ मा गृ॑धः॒ कस्य॑ स्वि॒द्धन॑म्॥१॥",
      transliteration: "oṃ īśā vāsyam idaṃ sarvaṃ yat kiñca jagatyāṃ jagat |\ntena tyaktena bhuñjīthā mā gṛdhaḥ kasya svid dhanam || 1 ||",
      hindiTranslation: "इस गतिशील संसार में जो कुछ भी जड़-चेतन जगत है, वह सब ईश्वर से व्याप्त है। अतः त्यागभाव से उसका भोग करो; किसी के धन-ऐश्वर्य का लोभ मत करो।",
      englishTranslation: "All this, whatever moves in this moving world, is enveloped and indwelt by the Divine Lord. Therefore enjoy through renunciation; covet not the wealth of anyone.",
      hinglishTranslation: "Is poore jagat me jo kuch bhi hai, sabme Ishwar vyapt hai. Isliye tyagbhav se upbhog karo, kisi ke dhan ka lalach mat karo.",
      padapatha: [
        { word: "ई॒शा", meaning: "ईश्वर से" },
        { word: "वा॒स्य॑म्", meaning: "आच्छादित/व्याप्त" },
        { word: "इ॒दम्", meaning: "यह" },
        { word: "सर्व॑म्", meaning: "सब कुछ" },
        { word: "यत्", meaning: "जो" },
        { word: "किञ्च॑", meaning: "कुछ भी" },
        { word: "जग॑त्याम्", meaning: "संसार में" },
        { word: "जग॑त्", meaning: "जगत" },
        { word: "तेन॑", meaning: "उसके द्वारा" },
        { word: "त्य॒क्तेन॑", meaning: "त्यागपूर्वक" },
        { word: "भु॒ञ्जी॒थाः॒", meaning: "भोग करो" },
        { word: "मा", meaning: "मत" },
        { word: "गृ॒धः॒", meaning: "लोभ करो" }
      ],
      shastricContext: "उपनिषदों का शिरोमणि आदि मन्त्र। यह मन्त्र वेदान्त और कर्मयोग का प्राण है।",
      orderIndex: 9,
      status: "ACTIVE"
    },
    {
      id: "yj-40-2",
      slug: "yj-40-2",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-40",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "ईशावास्योपनिषद्",
      sectionRef: "अध्याय ४०, मन्त्र २",
      mantraNumber: "४०.२",
      rishi: "दध्यङ् आथर्वण",
      devata: "कर्मयोग / आत्मा",
      chhanda: "अनुष्टुप्",
      svara: "सस्वर वैदिक पाठ",
      sanskrit: "कु॒र्वन्ने॒वेह कर्मा॑णि जिजीवि॒षेच्छ॒तं समाः॑।\nए॒वं त्वयि॒ नान्यथे॒तो॑ऽस्ति॒ न कर्म॑ लिप्यते॒ नरे॑॥२॥",
      transliteration: "kurvann eveha karmāṇi jijīviṣec chataṃ samāḥ |\nevaṃ tvayi nānyatheto'sti na karma lipyate nare || 2 ||",
      hindiTranslation: "इस संसार में निष्काम भाव से शास्त्र-सम्मत कर्तव्य-कर्म करते हुए ही सौ वर्ष जीने की इच्छा करनी चाहिए। तुम्हारे लिए इसके अतिरिक्त अन्य कोई मार्ग नहीं है; इस प्रकार कर्म करने से मनुष्य कर्म-बन्धन में लिप्त नहीं होता।",
      englishTranslation: "Performing righteous works alone in this world, one should desire to live a hundred years. Thus for thee, and not otherwise, actions will not adhere or bind unto man.",
      hinglishTranslation: "Is sansar me nishkam bhav se satkarma karte hue hi 100 saal jeene ki iccha karni chahiye. Iske alawa doosra rasta nahi hai, aise karm karne se manushya bandhan me nahi padta.",
      padapatha: [
        { word: "कु॒र्वन्", meaning: "करता हुआ" },
        { word: "ए॒व", meaning: "ही" },
        { word: "इ॒ह", meaning: "इस संसार में" },
        { word: "कर्मा॑णि", meaning: "कर्तव्य कर्मों को" },
        { word: "जि॒जी॒वि॒षेत्", meaning: "जीने की इच्छा करे" },
        { word: "श॒तम्", meaning: "सौ" },
        { word: "समाः॑", meaning: "वर्ष" },
        { word: "न", meaning: "नहीं" },
        { word: "कर्म॑", meaning: "कर्म" },
        { word: "लि॒प्य॒ते॒", meaning: "लिप्त होता" },
        { word: "नरे॑", meaning: "मनुष्य में" }
      ],
      shastricContext: "भगवद्गीता के निष्काम कर्मयोग का वैदिक उद्गम। कर्म का त्याग नहीं, वरन् फल की आसक्ति का त्याग सिखाता है।",
      orderIndex: 10,
      status: "ACTIVE"
    },
    {
      id: "yj-40-16",
      slug: "yj-40-16",
      vedaId: "yajurveda",
      nodeId: "yj-adhyaya-40",
      vedaName: "यजुर्वेद (Yajurveda)",
      shakha: "शुक्ल यजुर्वेद वाजसनेयि माध्यन्दिना",
      textName: "ईशावास्योपनिषद्",
      sectionRef: "अध्याय ४०, मन्त्र १६",
      mantraNumber: "४०.१६",
      rishi: "दध्यङ् आथर्वण",
      devata: "सूर्य / सोऽहमस्मि",
      chhanda: "त्रिष्टुप्",
      svara: "सस्वर वैदिक पाठ",
      sanskrit: "पूष॑न्नेकर्षे यम॒ सूर्य॑ प्राजाप॒त्य व्यू॑ह र॒श्मीन्समू॑ह॒ तेजः॑।\nयत्ते॑ रू॒पं क॒ल्या॑णतमं॒ तत्ते॑ पश्यामि॒ योऽसा॑व॒सौ पुरु॑षः॒ सोऽहम॑स्मि॥१६॥",
      transliteration: "pūṣann ekarṣe yama sūrya prājāpatya vyūha raśmīn samūha tejaḥ |\nyat te rūpaṃ kalyāṇatamaṃ tat te paśyāmi yo'sāv asau puruṣaḥ so'ham asmi || 16 ||",
      hindiTranslation: "हे पोषक पूषन्! हे एकाकी ज्ञाता! हे यम, हे सूर्य, हे प्रजापति-नन्दन! अपनी तीक्ष्ण किरणों को समेटिए, अपने प्रचण्ड तेज को समेटिए। आपकी जो परम कल्याणमयी ज्योतिर्मय मूर्ति है, मैं उसे आपके अनुग्रह से देख रहा हूँ। वह जो आदित्य-मण्डल में दिव्य पुरुष है, वह 'सोऽहम् अस्मि' (वह मैं ही हूँ)।",
      englishTranslation: "O Nourisher, solitary seer, controller, O Sun, offspring of Prajapati! Gather thy blinding rays, withdraw thy dazzling brilliance! May I behold Thine most auspicious form. That Supreme Person who dwells yonder—that very Person am I ('So'ham Asmi').",
      hinglishTranslation: "Hey Surya Dev! Apni tivra kirno ko sametiye. Aapka jo param mangalkari roop hai, use main dekh sakun. Wah jo divya purush hai, wah main hi hoon ('So'ham Asmi').",
      padapatha: [
        { word: "पूष॑न्", meaning: "हे सबका पोषण करने वाले" },
        { word: "एक-ऋषे", meaning: "हे अद्वितीय द्रष्टा" },
        { word: "यम॑", meaning: "हे नियन्ता" },
        { word: "सूर्य॑", meaning: "हे सूर्य" },
        { word: "व्यू॑ह", meaning: "हटाओ/फैलाओ" },
        { word: "र॒श्मीन्", meaning: "किरणों को" },
        { word: "समू॑ह", meaning: "समेटो" },
        { word: "तेजः॑", meaning: "तेज को" },
        { word: "क॒ल्या॑ण-तमम्", meaning: "कल्याणकारी" },
        { word: "सः", meaning: "वह" },
        { word: "अ॒हम्", meaning: "मैं" },
        { word: "अ॒स्मि॒", meaning: "हूँ" }
      ],
      shastricContext: "वेदान्त का अमर महावाक्य 'सोऽहमस्मि' (I am He)। जीवात्मा और परमात्मा की ऐक्य अनुभूति का चरम वैदिक उद्घोष।",
      orderIndex: 11,
      status: "ACTIVE"
    },
    {
      id: "yj-kr-1-1",
      slug: "yj-kr-1-1",
      vedaId: "yajurveda",
      nodeId: "taittiriya-upanishad",
      vedaName: "यजुर्वेद (कृष्ण यजुर्वेद)",
      shakha: "तैत्तिरीय शाखा",
      textName: "तैत्तिरीय उपनिषद् (शिक्षावल्ली)",
      sectionRef: "शिक्षावल्ली, अनुवाक ११",
      mantraNumber: "१.११.१",
      rishi: "त्रिशङ्कु",
      devata: "धर्म एवं सत्य",
      chhanda: "यजुः सूत्र",
      svara: "सस्वर वैदिक पाठ (तैत्तिरीय स्वर)",
      sanskrit: "स॒त्यं व॑द। ध॒र्मं च॑र। स्वा॒ध्या॒यान्मा प्र॑मदः। आ॒चा॒र्या॑य प्रि॒यं धन॒माहृ॑त्य प्र॒जात॑न्तुं मा व्य॑वच्छेत्सीः॥",
      transliteration: "satyaṃ vada | dharmaṃ cara | svādhyāyān mā pramadaḥ | ācāryāya priyaṃ dhanam āhṛtya prajā-tantuṃ mā vyavacchetsīḥ ||",
      hindiTranslation: "सदा सत्य बोलो। धर्म का आचरण करो। स्वाध्याय (आत्म-अध्ययन) में कभी प्रमाद मत करो। आचार्य को प्रिय दक्षिणा भेंट कर गृहस्थाश्रम में संतान-परम्परा को मत तोड़ो।",
      englishTranslation: "Speak the truth. Practice righteousness. Do not neglect self-study and learning. Having offered desirable gifts to the teacher, cut not off the thread of progeny.",
      hinglishTranslation: "Satya bolo. Dharma ka aacharan karo. Swadhyay me alasya mat karo. Guru ko dakshina dekar vansha parampara ko aage badhao.",
      padapatha: [
        { word: "स॒त्यम्", meaning: "सत्य को" },
        { word: "व॒द॒", meaning: "बोलो" },
        { word: "ध॒र्मम्", meaning: "धर्म का" },
        { word: "च॒र॒", meaning: "आचरण करो" },
        { word: "स्वा॒ध्या॒यात्", meaning: "स्वाध्याय से" },
        { word: "मा", meaning: "मत" },
        { word: "प्र॒म॒दः॒", meaning: "प्रमाद करो" }
      ],
      shastricContext: "सनातन गुरुकुलों का दीक्षांत अनुशासन। भारतीय जीवन मूल्यों का सर्वोच्च आधार।",
      orderIndex: 12,
      status: "ACTIVE"
    }
  ]
};

fs.writeFileSync(targetPath, JSON.stringify(yajurvedaData, null, 2), 'utf-8');
console.log('Successfully written yajurveda_curated.json! Nodes:', yajurvedaData.nodes.length, 'Mantras:', yajurvedaData.mantras.length);
