/**
 * Comprehensive Vedic Heritage Portal Dataset Generator
 * Sourced from the Government of India's Vedic Heritage Portal (vedicheritage.gov.in)
 * All 4 Vedas: Rigveda, Yajurveda, Samaveda, and Atharvaveda
 */

const fs = require("fs");
const path = require("path");

const VEDAS = [
  {
    id: "rigveda",
    slug: "rigveda",
    name: "ऋग्वेद",
    enName: "Rigveda",
    eyebrow: "प्रधान श्रुति",
    intro: "ऋचाओं और सूक्तों का प्राचीनतम वैदिक संग्रह। स्तुति, ज्ञान, विज्ञान और आध्यात्मिक चेतना का मूल स्रोत।",
    badge: "ऋत्विक: होतृ (Hotri)",
    chiefPriest: "होतृ (Hotri)",
    mandalaCount: "१० मण्डल",
    suktaCount: "१०२८ सूक्त",
    mantraCount: "१०,५५२ मन्त्र",
    chiefRishis: "मधुच्छन्दा, गृत्समद, विश्वामित्र, वामदेव, अत्रि, भारद्वाज, वसिष्ठ, दीर्घतमा",
    language: "वैदिक संस्कृत (छान्दस)",
    overview: "ऋग्वेद मानव जाति का सबसे प्राचीन उपलब्ध ग्रंथ है। इसमें १० मण्डल, १०२८ सूक्त और १०,५५२ ऋचाएँ हैं। यह अग्नि, इन्द्र, वरुण, सूर्य, उषा आदि प्राकृतिक व दिव्य शक्तियों के माध्यम से परब्रह्म की स्तुति करता है। 'एकं सद्विप्रा बहुधा वदन्ति' (१.१६४.४६) और प्रसिद्ध गायत्री महामन्त्र (३.६२.१०) इसी वेद के अमर सन्देश हैं।",
    statsLine: "१० मण्डल • १०२८ सूक्त • १०,५५२ मंत्र",
    status: "ACTIVE",
    orderIndex: 1
  },
  {
    id: "yajurveda",
    slug: "yajurveda",
    name: "यजुर्वेद",
    enName: "Yajurveda",
    eyebrow: "कर्मकाण्ड एवं ज्ञान",
    intro: "यज्ञ, कर्म एवं अनुष्ठानिक क्रियाओं का वेद। शुक्ल और कृष्ण शाखा परंपरा में विभक्त।",
    badge: "ऋत्विक: अध्वर्यु (Adhvaryu)",
    chiefPriest: "अध्वर्यु (Adhvaryu)",
    mandalaCount: "४० अध्याय (शुक्ल)",
    suktaCount: "१९७५ कण्डिकाएँ",
    mantraCount: "१९७५ मन्त्र",
    chiefRishis: "याज्ञवल्क्य, तित्तिरि, वैशम्पायन",
    language: "वैदिक संस्कृत (गद्य-पद्यात्मक)",
    overview: "यजुर्वेद यज्ञीय कर्मकाण्ड, राष्ट्र की उन्नति और आध्यात्मिक चेतना का समन्वय है। शुक्ल यजुर्वेद की माध्यन्दिन वाजसनेयि शाखा का ४०वाँ अध्याय प्रसिद्ध 'ईशावास्योपनिषद्' है। इसी वेद में 'शतरुद्रीय' (रुद्राष्टाध्यायी) और 'शिवसंकल्प सूक्त' प्रतिष्ठित हैं।",
    statsLine: "४० अध्याय • १९७५ मंत्र • शुक्ल व कृष्ण शाखाएँ",
    status: "ACTIVE",
    orderIndex: 2
  },
  {
    id: "samaveda",
    slug: "samaveda",
    name: "सामवेद",
    enName: "Samaveda",
    eyebrow: "संगीत एवं उपासना",
    intro: "गायकी, संगीतमय ऋचाओं एवं सामगान का दिव्य वेद। भगवान श्रीकृष्ण ने गीता में कहा: 'वेदानां सामवेदोऽस्मि'।",
    badge: "ऋत्विक: उद्गातृ (Udgatri)",
    chiefPriest: "उद्गातृ (Udgatri)",
    mandalaCount: "२ आर्चिक (पूर्वार्चिक व उत्तरार्चिक)",
    suktaCount: "६ प्रपाठक",
    mantraCount: "१८७५ मन्त्र",
    chiefRishis: "जैमिनि, सुधन्वा, सुकर्मा",
    language: "वैदिक संस्कृत (स्वर-संगीत बद्ध)",
    overview: "सामवेद भारतीय शास्त्रीय संगीत का मूल उद्गम स्रोत है। इसमें ऋग्वेद की ऋचाओं को सात स्वरों (सा, रे, ग, म, प, ध, नि) में गायन योग्य रूप में प्रस्तुत किया गया है। इसकी कौथुम, राणायनीय और जैमिनीय शाखाएँ प्रसिद्ध हैं। छान्दोग्योपनिषद् इसी सामवेद की कौथुम शाखा से सम्बद्ध है।",
    statsLine: "१८७५ मंत्र • कौथुम, राणायनीय, जैमिनीय",
    status: "ACTIVE",
    orderIndex: 3
  },
  {
    id: "atharvaveda",
    slug: "atharvaveda",
    name: "अथर्ववेद",
    enName: "Atharvaveda",
    eyebrow: "ब्रह्मवेद एवं विज्ञान",
    intro: "ब्रह्मवेद — आयुर्वेद, भैषज्य, शांति-पौष्टिक कर्म, राष्ट्र-रक्षा, गणित, वास्तु एवं गूढ़ अध्यात्म का संग्रह।",
    badge: "ऋत्विक: ब्रह्मा (Brahma)",
    chiefPriest: "ब्रह्मा (Brahma)",
    mandalaCount: "२० काण्ड",
    suktaCount: "७३० सूक्त",
    mantraCount: "५,९७७ मन्त्र",
    chiefRishis: "अथर्वा, अङ्गिरा, भृगु",
    language: "वैदिक संस्कृत",
    overview: "अथर्ववेद को ब्रह्मवेद भी कहा जाता है क्योंकि इसके ऋत्विक 'ब्रह्मा' यज्ञ के संपूर्ण अध्यक्ष होते हैं। इसमें १२वें काण्ड का 'भूमि सूक्त' (माता भूमिः पुत्रोऽहं पृथिव्याः) राष्ट्रप्रेम और पर्यावरण चेतना का विश्व-प्रथम घोषणापत्र है। इसके अतिरिक्त आयुर्वेद, राजकर्म, शान्ति-कर्म और मांडूक्योपनिषद् (सत्यमेव जयते) इसी वेद की देन हैं।",
    statsLine: "२० काण्ड • ७३० सूक्त • ५,९७७ मंत्र",
    status: "ACTIVE",
    orderIndex: 4
  }
];

const NODES = [
  // ================= RIGVEDA NODES =================
  { id: "shakala-shakha", vedaId: "rigveda", parentId: null, slug: "shakala-shakha", title: "शाकल शाखा", enTitle: "Shakala Shakha", type: "SHAKHA", orderIndex: 1 },
  { id: "rv-samhita", vedaId: "rigveda", parentId: "shakala-shakha", slug: "rv-samhita", title: "ऋग्वेद संहिता", enTitle: "Rigveda Samhita", type: "SAMHITA", orderIndex: 1 },
  
  // Mandalas
  { id: "rv-mandala-1", vedaId: "rigveda", parentId: "rv-samhita", slug: "rv-mandala-1", title: "प्रथम मण्डल (अग्नि सूक्त)", enTitle: "Mandala 1", type: "MANDALA", orderIndex: 1 },
  { id: "rv-mandala-3", vedaId: "rigveda", parentId: "rv-samhita", slug: "rv-mandala-3", title: "तृतीय मण्डल (गायत्री सूक्त)", enTitle: "Mandala 3", type: "MANDALA", orderIndex: 3 },
  { id: "rv-mandala-7", vedaId: "rigveda", parentId: "rv-samhita", slug: "rv-mandala-7", title: "सप्तम मण्डल (महामृत्युंजय सूक्त)", enTitle: "Mandala 7", type: "MANDALA", orderIndex: 7 },
  { id: "rv-mandala-10", vedaId: "rigveda", parentId: "rv-samhita", slug: "rv-mandala-10", title: "दशम मण्डल (दार्शनिक सूक्त)", enTitle: "Mandala 10", type: "MANDALA", orderIndex: 10 },

  // Suktas
  { id: "rv-sukta-1", vedaId: "rigveda", parentId: "rv-mandala-1", slug: "rv-sukta-1", title: "सूक्त १ (अग्नि सूक्त)", enTitle: "Agni Sukta (1.1)", type: "SUKTA", orderIndex: 1, mantraId: "rv-1-1-1" },
  { id: "rv-sukta-3-62", vedaId: "rigveda", parentId: "rv-mandala-3", slug: "rv-sukta-3-62", title: "सूक्त ६२ (सविता / गायत्री सूक्त)", enTitle: "Savitr / Gayatri Sukta (3.62)", type: "SUKTA", orderIndex: 1, mantraId: "rv-3-62-10" },
  { id: "rv-sukta-7-59", vedaId: "rigveda", parentId: "rv-mandala-7", slug: "rv-sukta-7-59", title: "सूक्त ५९ (महामृत्युंजय / रुद्र सूक्त)", enTitle: "Mahamrityunjaya Sukta (7.59)", type: "SUKTA", orderIndex: 1, mantraId: "rv-7-59-12" },
  { id: "rv-sukta-10-90", vedaId: "rigveda", parentId: "rv-mandala-10", slug: "rv-sukta-10-90", title: "सूक्त ९० (पुरुष सूक्त)", enTitle: "Purusha Sukta (10.90)", type: "SUKTA", orderIndex: 1, mantraId: "rv-10-90-1" },
  { id: "rv-sukta-10-121", vedaId: "rigveda", parentId: "rv-mandala-10", slug: "rv-sukta-10-121", title: "सूक्त १२१ (हिरण्यगर्भ सूक्त)", enTitle: "Hiranyagarbha Sukta (10.121)", type: "SUKTA", orderIndex: 2, mantraId: "rv-10-121-1" },
  { id: "rv-sukta-10-125", vedaId: "rigveda", parentId: "rv-mandala-10", slug: "rv-sukta-10-125", title: "सूक्त १२५ (देवी / वाक् सूक्त)", enTitle: "Devi / Vak Sukta (10.125)", type: "SUKTA", orderIndex: 3, mantraId: "rv-10-125-1" },
  { id: "rv-sukta-10-129", vedaId: "rigveda", parentId: "rv-mandala-10", slug: "rv-sukta-10-129", title: "सूक्त १२९ (नासदीय सूक्त - सृष्टि उत्पत्ति)", enTitle: "Nasadiya Sukta (10.129)", type: "SUKTA", orderIndex: 4, mantraId: "rv-10-129-1" },
  { id: "rv-sukta-10-191", vedaId: "rigveda", parentId: "rv-mandala-10", slug: "rv-sukta-10-191", title: "सूक्त १९१ (संज्ञान / संगठन सूक्त)", enTitle: "Samjnana Sukta (10.191)", type: "SUKTA", orderIndex: 5, mantraId: "rv-10-191-2" },

  // Brahmanas & Upanishads for Rigveda
  { id: "rv-aitareya-brahmana", vedaId: "rigveda", parentId: "shakala-shakha", slug: "aitareya-brahmana", title: "ऐतरेय ब्राह्मण", enTitle: "Aitareya Brahmana", type: "BRAHMANA", orderIndex: 2 },
  { id: "rv-aitareya-upanishad", vedaId: "rigveda", parentId: "shakala-shakha", slug: "aitareya-upanishad", title: "ऐतरेय उपनिषद्", enTitle: "Aitareya Upanishad", type: "UPANISHAD", orderIndex: 3 },

  // ================= YAJURVEDA NODES =================
  { id: "shukla-yajurveda", vedaId: "yajurveda", parentId: null, slug: "shukla-yajurveda", title: "शुक्ल यजुर्वेद (माध्यन्दिन वाजसनेयि)", enTitle: "Shukla Yajurveda", type: "SHAKHA", orderIndex: 1 },
  { id: "vajasaneyi-samhita", vedaId: "yajurveda", parentId: "shukla-yajurveda", slug: "vajasaneyi-samhita", title: "वाजसनेयि संहिता (माध्यन्दिन)", enTitle: "Vajasaneyi Samhita", type: "SAMHITA", orderIndex: 1 },
  { id: "yj-adhyaya-1", vedaId: "yajurveda", parentId: "vajasaneyi-samhita", slug: "yj-adhyaya-1", title: "अध्याय १ (दर्शपूर्णमास यज्ञ आरम्भ)", enTitle: "Adhyaya 1 (Yajna Aarambha)", type: "ADHYAYA", orderIndex: 1, mantraId: "yj-1-1" },
  { id: "yj-adhyaya-16", vedaId: "yajurveda", parentId: "vajasaneyi-samhita", slug: "yj-adhyaya-16", title: "अध्याय १६ (शतरुद्रीय / रुद्राष्टाध्यायी)", enTitle: "Adhyaya 16 (Shri Rudram)", type: "ADHYAYA", orderIndex: 2, mantraId: "yj-16-1" },
  { id: "yj-adhyaya-22", vedaId: "yajurveda", parentId: "vajasaneyi-samhita", slug: "yj-adhyaya-22", title: "अध्याय २२ (राष्ट्र समृद्धि प्रार्थना)", enTitle: "Adhyaya 22 (Rashtra Samriddhi)", type: "ADHYAYA", orderIndex: 3, mantraId: "yj-22-22" },
  { id: "yj-adhyaya-34", vedaId: "yajurveda", parentId: "vajasaneyi-samhita", slug: "yj-adhyaya-34", title: "अध्याय ३४ (शिवसंकल्प सूक्त)", enTitle: "Adhyaya 34 (Shiva Sankalpa Sukta)", type: "ADHYAYA", orderIndex: 4, mantraId: "yj-34-1" },
  { id: "yj-adhyaya-36", vedaId: "yajurveda", parentId: "vajasaneyi-samhita", slug: "yj-adhyaya-36", title: "अध्याय ३६ (विश्व शान्ति पाठ)", enTitle: "Adhyaya 36 (Vishva Shanti Patha)", type: "ADHYAYA", orderIndex: 5, mantraId: "yj-36-17" },
  { id: "yj-adhyaya-40", vedaId: "yajurveda", parentId: "vajasaneyi-samhita", slug: "yj-adhyaya-40", title: "अध्याय ४० (ईशावास्योपनिषद्)", enTitle: "Adhyaya 40 (Ishavasya Upanishad)", type: "UPANISHAD", orderIndex: 6, mantraId: "yj-40-1" },
  { id: "shatapatha-brahmana", vedaId: "yajurveda", parentId: "shukla-yajurveda", slug: "shatapatha-brahmana", title: "शतपथ ब्राह्मण", enTitle: "Shatapatha Brahmana", type: "BRAHMANA", orderIndex: 2 },
  { id: "brihadaranyaka-upanishad", vedaId: "yajurveda", parentId: "shukla-yajurveda", slug: "brihadaranyaka-upanishad", title: "बृहदारण्यक उपनिषद्", enTitle: "Brihadaranyaka Upanishad", type: "UPANISHAD", orderIndex: 3 },

  // Krishna Yajurveda
  { id: "krishna-yajurveda", vedaId: "yajurveda", parentId: null, slug: "krishna-yajurveda", title: "कृष्ण यजुर्वेद (तैत्तिरीय)", enTitle: "Krishna Yajurveda", type: "SHAKHA", orderIndex: 2 },
  { id: "taittiriya-samhita", vedaId: "yajurveda", parentId: "krishna-yajurveda", slug: "taittiriya-samhita", title: "तैत्तिरीय संहिता", enTitle: "Taittiriya Samhita", type: "SAMHITA", orderIndex: 1 },
  { id: "taittiriya-brahmana", vedaId: "yajurveda", parentId: "krishna-yajurveda", slug: "taittiriya-brahmana", title: "तैत्तिरीय ब्राह्मण", enTitle: "Taittiriya Brahmana", type: "BRAHMANA", orderIndex: 2 },
  { id: "taittiriya-upanishad", vedaId: "yajurveda", parentId: "krishna-yajurveda", slug: "taittiriya-upanishad", title: "तैत्तिरीय उपनिषद् (शिक्षावल्ली)", enTitle: "Taittiriya Upanishad", type: "UPANISHAD", orderIndex: 3, mantraId: "yj-kr-1-1" },

  // ================= SAMAVEDA NODES =================
  { id: "kauthuma-shakha", vedaId: "samaveda", parentId: null, slug: "kauthuma-shakha", title: "कौथुम शाखा", enTitle: "Kauthuma Shakha", type: "SHAKHA", orderIndex: 1 },
  { id: "kauthuma-samhita", vedaId: "samaveda", parentId: "kauthuma-shakha", slug: "kauthuma-samhita", title: "सामवेद संहिता (कौथुम)", enTitle: "Kauthuma Samhita", type: "SAMHITA", orderIndex: 1 },
  { id: "sv-poorvarchik", vedaId: "samaveda", parentId: "kauthuma-samhita", slug: "sv-poorvarchik", title: "पूर्वार्चिक (छन्द आर्ची)", enTitle: "Purvarchika", type: "KANDA", orderIndex: 1 },
  { id: "sv-agneya-kanda", vedaId: "samaveda", parentId: "sv-poorvarchik", slug: "sv-agneya-kanda", title: "आग्नेय काण्ड (प्रथम प्रपाठक)", enTitle: "Agneya Kanda", type: "SUKTA", orderIndex: 1, mantraId: "sv-1-1-1" },
  { id: "sv-aindra-parva", vedaId: "samaveda", parentId: "sv-poorvarchik", slug: "sv-aindra-parva", title: "ऐन्द्र पर्व (द्वितीय प्रपाठक)", enTitle: "Aindra Parva", type: "SUKTA", orderIndex: 2, mantraId: "sv-1-2-1" },
  { id: "sv-pavamana-kanda", vedaId: "samaveda", parentId: "sv-poorvarchik", slug: "sv-pavamana-kanda", title: "पवमान काण्ड (सोम स्तुति)", enTitle: "Pavamana Kanda", type: "SUKTA", orderIndex: 3, mantraId: "sv-2-1-1" },
  { id: "sv-aranya-kanda", vedaId: "samaveda", parentId: "sv-poorvarchik", slug: "sv-aranya-kanda", title: "अरण्य काण्ड व महानाम्नी", enTitle: "Aranya Kanda", type: "SUKTA", orderIndex: 4 },
  { id: "sv-uttararchik", vedaId: "samaveda", parentId: "kauthuma-samhita", slug: "sv-uttararchik", title: "उत्तरार्चिक (गान पद)", enTitle: "Uttararchika", type: "KANDA", orderIndex: 2 },
  { id: "chandogya-upanishad", vedaId: "samaveda", parentId: "kauthuma-shakha", slug: "chandogya-upanishad", title: "छान्दोग्य उपनिषद् (उद्गीथ उपासना)", enTitle: "Chandogya Upanishad", type: "UPANISHAD", orderIndex: 3, mantraId: "sv-ch-1-1" },
  { id: "jaiminiya-shakha", vedaId: "samaveda", parentId: null, slug: "jaiminiya-shakha", title: "जैमिनीय (तलवकार) शाखा", enTitle: "Jaiminiya Shakha", type: "SHAKHA", orderIndex: 2 },

  // ================= ATHARVAVEDA NODES =================
  { id: "shaunaka-shakha", vedaId: "atharvaveda", parentId: null, slug: "shaunaka-shakha", title: "शौनक शाखा", enTitle: "Shaunaka Shakha", type: "SHAKHA", orderIndex: 1 },
  { id: "shaunaka-samhita", vedaId: "atharvaveda", parentId: "shaunaka-shakha", slug: "shaunaka-samhita", title: "अथर्ववेद संहिता (शौनक)", enTitle: "Shaunaka Samhita", type: "SAMHITA", orderIndex: 1 },
  { id: "av-kanda-1-sukta-1", vedaId: "atharvaveda", parentId: "shaunaka-samhita", slug: "av-kanda-1-sukta-1", title: "काण्ड १, सूक्त १ (मेधाजनन सूक्त)", enTitle: "Medha Janana Sukta (1.1)", type: "SUKTA", orderIndex: 1, mantraId: "av-1-1-1" },
  { id: "av-kanda-1-sukta-2", vedaId: "atharvaveda", parentId: "shaunaka-samhita", slug: "av-kanda-1-sukta-2", title: "काण्ड १, सूक्त २ (आयुष्य एवं रोगनिवारण सूक्त)", enTitle: "Ayushya & Healing Sukta (1.2)", type: "SUKTA", orderIndex: 2, mantraId: "av-1-2-1" },
  { id: "av-kanda-10-skambha", vedaId: "atharvaveda", parentId: "shaunaka-samhita", slug: "av-kanda-10-skambha", title: "काण्ड १०, सूक्त ७ (स्कम्भ सूक्त - ब्रह्माण्ड स्तम्भ)", enTitle: "Skambha Sukta (10.7)", type: "SUKTA", orderIndex: 3, mantraId: "av-10-7-1" },
  { id: "av-kanda-11-brahmacharya", vedaId: "atharvaveda", parentId: "shaunaka-samhita", slug: "av-kanda-11-brahmacharya", title: "काण्ड ११, सूक्त ५ (ब्रह्मचर्य सूक्त)", enTitle: "Brahmacharya Sukta (11.5)", type: "SUKTA", orderIndex: 4, mantraId: "av-11-5-1" },
  { id: "av-kanda-12-bhumi", vedaId: "atharvaveda", parentId: "shaunaka-samhita", slug: "av-kanda-12-bhumi", title: "काण्ड १२, सूक्त १ (पृथ्वी / भूमि सूक्त)", enTitle: "Prithvi / Bhumi Sukta (12.1)", type: "SUKTA", orderIndex: 5, mantraId: "av-12-1-12" },
  { id: "av-kanda-19-shanti", vedaId: "atharvaveda", parentId: "shaunaka-samhita", slug: "av-kanda-19-shanti", title: "काण्ड १९, सूक्त ९ (विश्व शान्ति सूक्त)", enTitle: "Vishva Shanti Sukta (19.9)", type: "SUKTA", orderIndex: 6, mantraId: "av-19-9-14" },
  { id: "gopatha-brahmana", vedaId: "atharvaveda", parentId: "shaunaka-shakha", slug: "gopatha-brahmana", title: "गोपथ ब्राह्मण", enTitle: "Gopatha Brahmana", type: "BRAHMANA", orderIndex: 2 },
  { id: "mandukya-upanishad", vedaId: "atharvaveda", parentId: "shaunaka-shakha", slug: "mandukya-upanishad", title: "माण्डूक्य उपनिषद् (सत्यमेव जयते)", enTitle: "Mandukya Upanishad", type: "UPANISHAD", orderIndex: 3 },
  { id: "paippalada-shakha", vedaId: "atharvaveda", parentId: null, slug: "paippalada-shakha", title: "पैप्पलाद शाखा", enTitle: "Paippalada Shakha", type: "SHAKHA", orderIndex: 2 }
];

const MANTRAS = [
  // =========================================================================
  // RIGVEDA MANTRAS (vedicheritage.gov.in Shakala Samhita)
  // =========================================================================
  {
    id: "rv-1-1-1",
    vedaId: "rigveda",
    nodeId: "rv-sukta-1",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (अग्नि सूक्त)",
    sectionRef: "मण्डल १, सूक्त १",
    mantraNumber: "१.१.१",
    rishi: "मधुच्छन्दा वैश्वामित्र",
    devata: "अग्नि (Agni - Purohita)",
    chhanda: "गायत्री (८+८+८ = २४ वर्ण)",
    svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
    sanskrit: "ॐ अ॒ग्निमी॑ळे पु॒रोहि॑तं य॒ज्ञस्य॑ दे॒वमृ॒त्विज॑म्।\nहोता॑रं रत्न॒धात॑मम्॥१॥",
    transliteration: "oṃ agnim īḷe purohitaṃ yajñasya devam ṛtvijam |\nhotāraṃ ratnadhātamam || 1 ||",
    hindiTranslation: "मैं यज्ञ के पुरोहित, दिव्य प्रकाशवान, ऋत्विक् और आह्वानकर्ता अग्निदेव की स्तुति करता हूँ, जो सर्वश्रेष्ठ रत्नों को धारण कराने वाले हैं।",
    englishTranslation: "I magnify Agni, the divine priest of sacrifice, the radiant officiant and summoner who bestows the highest spiritual and material treasures.",
    hinglishTranslation: "Main yagya ke purohit, divya prakashmay Agni Dev ki stuti karta hoon jo aahwan karne wale aur shreshtha ratno ke data hain.",
    padapatha: [
      { word: "अ॒ग्निम्", meaning: "अग्निदेव को" },
      { word: "ई॒ळे", meaning: "स्तुति करता हूँ" },
      { word: "पु॒रो-हि॑तम्", meaning: "यज्ञ के अग्रभाग में स्थापित पुरोहित को" },
      { word: "य॒ज्ञस्य॑", meaning: "यज्ञ के" },
      { word: "दे॒वम्", meaning: "प्रकाशमान देव को" },
      { word: "ऋ॒त्विज॑म्", meaning: "ऋतु-ऋतु में यज्ञ सम्पन्न कराने वाले ऋत्विक् को" },
      { word: "होता॑रम्", meaning: "देवताओं का आह्वान करने वाले को" },
      { word: "र॒त्न॒-धात॑मम्", meaning: "उत्कृष्ट रत्नों व ऐश्वर्य के परम धारक को" }
    ],
    shastricContext: "ऋग्वेद का प्रथम मंगलाचरण मंत्र। अग्निदेव को ब्रह्म के प्रथम प्रत्यक्ष रूप में स्थापित कर आत्मोन्नति की प्रार्थना की गई है।",
    orderIndex: 1,
    status: "ACTIVE"
  },
  {
    id: "rv-1-1-2",
    vedaId: "rigveda",
    nodeId: "rv-sukta-1",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (अग्नि सूक्त)",
    sectionRef: "मण्डल १, सूक्त १",
    mantraNumber: "१.१.२",
    rishi: "मधुच्छन्दा वैश्वामित्र",
    devata: "अग्नि",
    chhanda: "गायत्री",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "अ॒ग्निः पूर्वे॑भि॒रृषि॑भि॒रीड्यो॒ नूत॑नैरु॒त।\nस दे॒वाँ एह व॑क्षति॥२॥",
    transliteration: "agniḥ pūrvebhir ṛṣibhir īḍyo nūtanair uta |\nsa devāṃ eha vakṣati || 2 ||",
    hindiTranslation: "अग्निदेव पूर्वकाल के भृगु, अङ्गिरा आदि ऋषियों द्वारा पूजित रहे हैं और वर्तमान नए ऋषियों द्वारा भी स्तुत्य हैं। वे इस यज्ञ में सभी दिव्य देवों को यहाँ लेकर आएं।",
    englishTranslation: "Agni, praised by ancient seers as well as by modern sages, may he conduct the divine deities hither unto this sacred sacrifice.",
    hinglishTranslation: "Agni dev pracheen rishiyo dwara bhi pujya the aur naye rishiyo dwara bhi. Ve is yagya me sabhi devtao ko padharne ke liye aahwan karein.",
    padapatha: [
      { word: "अ॒ग्निः", meaning: "अग्निदेव" },
      { word: "पूर्वे॑भिः", meaning: "प्राचीन ऋषियों द्वारा" },
      { word: "ऋषि॑भिः", meaning: "ऋषियों द्वारा" },
      { word: "ईड्यः॑", meaning: "स्तुति के योग्य" },
      { word: "नूत॑नैः", meaning: "नवीन ऋषियों द्वारा" },
      { word: "उ॒त", meaning: "और भी" },
      { word: "सः", meaning: "वह अग्नि" },
      { word: "दे॒वान्", meaning: "देवताओं को" },
      { word: "आ", meaning: "यहाँ" },
      { word: "इ॒ह", meaning: "इस यज्ञ में" },
      { word: "व॒क्ष॒ति", meaning: "लेकर आवे" }
    ],
    shastricContext: "सनातन ऋषि परम्परा की निरंतरता का प्रतीक। भूत और वर्तमान दोनों कालों में अग्नि ज्ञान की ज्योति हैं।",
    orderIndex: 2,
    status: "ACTIVE"
  },
  {
    id: "rv-1-1-3",
    vedaId: "rigveda",
    nodeId: "rv-sukta-1",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (अग्नि सूक्त)",
    sectionRef: "मण्डल १, सूक्त १",
    mantraNumber: "१.१.३",
    rishi: "मधुच्छन्दा वैश्वामित्र",
    devata: "अग्नि",
    chhanda: "गायत्री",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "अ॒ग्निना॑ र॒यिम॑श्नव॒त्पोष॑मे॒व दि॒वेदि॑वे।\nय॒शसं॑ वी॒रव॑त्तमम्॥३॥",
    transliteration: "agninā rayim aśnavat poṣam eva dive-dive |\nyaśasaṃ vīravattamam || 3 ||",
    hindiTranslation: "अग्नि के अनुग्रह से साधक प्रतिदिन पुष्टि-वर्धक ऐश्वर्य प्राप्त करता है, जो यशयुक्त और वीर सन्तानों से परिपूर्ण होता है।",
    englishTranslation: "Through Agni may the seeker gain nourishment and prosperity day by day, glorious and rich in valiant progeny.",
    hinglishTranslation: "Agni ke madhyam se sadhak har din pushtikarak aishwarya, kirti aur virata-sampanna samriddhi pata hai.",
    padapatha: [
      { word: "अ॒ग्निना॑", meaning: "अग्नि के द्वारा" },
      { word: "र॒यिम्", meaning: "दिव्य धन व ऐश्वर्य को" },
      { word: "अ॒श्न॒व॒त्", meaning: "प्राप्त करता है" },
      { word: "पोष॑म्", meaning: "पुष्टि को" },
      { word: "ए॒व", meaning: "ही" },
      { word: "दि॒वे-दि॑वे", meaning: "प्रतिदिन" },
      { word: "य॒शस॑म्", meaning: "यशस्वी" },
      { word: "वी॒र-व॑त्तमम्", meaning: "श्रेष्ठ वीरों से युक्त" }
    ],
    shastricContext: "सदाचार और समर्पण से प्राप्त होने वाली सतत भौतिक व आत्मिक समृद्धि का निरूपण।",
    orderIndex: 3,
    status: "ACTIVE"
  },
  {
    id: "rv-1-1-4",
    vedaId: "rigveda",
    nodeId: "rv-sukta-1",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (अग्नि सूक्त)",
    sectionRef: "मण्डल १, सूक्त १",
    mantraNumber: "१.१.४",
    rishi: "मधुच्छन्दा वैश्वामित्र",
    devata: "अग्नि",
    chhanda: "गायत्री",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "अग्ने॒ यं य॒ज्ञम॑ध्व॒रं वि॒श्वतः॑ परि॒भूरसि॑।\nस इद्दे॒वेषु॑ गच्छति॥४॥",
    transliteration: "agne yaṃ yajñam adhvaraṃ viśvataḥ paribhūr asi |\nsa id deveṣu gacchati || 4 ||",
    hindiTranslation: "हे अग्नि! जिस हिंसारहित निष्काम यज्ञ को तुम चारों ओर से सुरक्षित रखते हो, वही यज्ञ वस्तुतः दिव्य देवों तक पहुँचता है।",
    englishTranslation: "O Agni, whatever sacred, non-violent sacrifice you encompass on every side, that alone ascends unto the celestial gods.",
    hinglishTranslation: "Hey Agni, jis ahimsak pavitra yagya ki raksha aap charo taraf se karte hain, vahi yagya sach me divya devtao tak pahunchta hai.",
    padapatha: [
      { word: "अग्ने॑", meaning: "हे अग्नि" },
      { word: "यम्", meaning: "जिस" },
      { word: "य॒ज्ञम्", meaning: "यज्ञ को" },
      { word: "अ॒ध्व॒रम्", meaning: "हिंसारहित को" },
      { word: "वि॒श्वतः॑", meaning: "सब ओर से" },
      { word: "प॒रि॒-भूः", meaning: "व्याप्त/रक्षक" },
      { word: "असि॑", meaning: "होते हो" },
      { word: "सः", meaning: "वह ही" },
      { word: "इत्", meaning: "निश्चय ही" },
      { word: "दे॒वेषु॑", meaning: "देवों में" },
      { word: "ग॒च्छ॒ति", meaning: "पहुँचता है" }
    ],
    shastricContext: "अध्वर (अ-ध्वर = हिंसा रहित) यज्ञ की अवधारणा, जो शांति और परोपकार पर आधारित है।",
    orderIndex: 4,
    status: "ACTIVE"
  },
  {
    id: "rv-1-1-9",
    vedaId: "rigveda",
    nodeId: "rv-sukta-1",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (अग्नि सूक्त)",
    sectionRef: "मण्डल १, सूक्त १",
    mantraNumber: "१.१.९",
    rishi: "मधुच्छन्दा वैश्वामित्र",
    devata: "अग्नि",
    chhanda: "गायत्री",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "स नः॑ पि॒तेव॑ सू॒नवेऽग्ने॑ सूपाय॒नो भ॑व।\nसच॑स्वा नः स्व॒स्तये॑॥९॥",
    transliteration: "sa naḥ piteva sūnave 'gne sūpāyano bhava |\nsacasvā naḥ svastaye || 9 ||",
    hindiTranslation: "हे अग्नि! जिस प्रकार पिता अपने पुत्र के लिए सुलभ और कल्याणकारी होता है, उसी प्रकार आप हमारे लिए सुलभ बनिए। हमारे परम कल्याण के लिए सदा हमारे साथ रहिए।",
    englishTranslation: "O Agni, be as accessible and compassionate to us as a father is unto his son; abide closely with us for our supreme wellbeing.",
    hinglishTranslation: "Hey Agni Dev, jaise pita apne santan ke liye sahaj aur kalyankari hota hai, waise hi aap hamare liye sugam baniye aur hamare kalyan ke liye sath rahiye.",
    padapatha: [
      { word: "सः", meaning: "वह आप" },
      { word: "नः॑", meaning: "हमारे लिए" },
      { word: "पि॒ता-इ॑व", meaning: "पिता के समान" },
      { word: "सू॒नवे॑", meaning: "पुत्र के लिए" },
      { word: "अग्ने॑", meaning: "हे अग्नि" },
      { word: "सु॒-उ॒पाय॒नः", meaning: "सुगमता से प्राप्त होने वाले" },
      { word: "भ॒व॒", meaning: "होइए" },
      { word: "सच॑स्व", meaning: "साथ रहिए" },
      { word: "नः॑", meaning: "हमारे" },
      { word: "स्व॒स्तये॑", meaning: "कल्याण व मंगल के लिए" }
    ],
    shastricContext: "अग्नि सूक्त का अंतिम समापन मंत्र। ईश्वर और साधक के बीच वात्सल्य और पिता-पुत्र के प्रेमपूर्ण सम्बन्ध की पराकाष्ठा।",
    orderIndex: 9,
    status: "ACTIVE"
  },
  {
    id: "rv-3-62-10",
    vedaId: "rigveda",
    nodeId: "rv-sukta-3-62",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (गायत्री / सावित्री मन्त्र)",
    sectionRef: "मण्डल ३, सूक्त ६२",
    mantraNumber: "३.६२.१०",
    rishi: "गाथिनो विश्वामित्र",
    devata: "सविता (Savita - Divine Solar Intellect)",
    chhanda: "गायत्री (२४ वर्ण)",
    svara: "सस्वर वैदिक पाठ (उदात्त, अनुदात्त, स्वरित)",
    sanskrit: "ॐ तत्स॑वि॒तुर्वरे॑ण्यं॒ भर्गो॑ दे॒वस्य॑ धीमहि।\nधियो॒ यो नः॑ प्रचो॒दया॑त्॥१०॥",
    transliteration: "oṃ tat savitur vareṇyaṃ bhargo devasya dhīmahi |\ndhiyo yo naḥ pracodayāt || 10 ||",
    hindiTranslation: "हम उस परम पूजनीय, सृष्टिकर्ता सविता देव के सर्वश्रेष्ठ दिव्य पापनाशक तेज का ध्यान करते हैं, जो हमारी बुद्धियों को सत्कर्मों और सत्यमार्ग की ओर प्रेरित करे।",
    englishTranslation: "May we meditate upon that supreme, adorable radiance of the Divine Creator Savitr; may that divine illumination enlighten and inspire our intellects.",
    hinglishTranslation: "Hum us parampujya srishtikarta Savita Dev ke sarvashreshtha divya tej ka dhyan karte hain, jo hamari buddhi ko sanmarg par prerit kare.",
    padapatha: [
      { word: "तत्", meaning: "उस" },
      { word: "स॒वि॒तुः", meaning: "सृष्टिकर्ता सविता देव के" },
      { word: "वरे॑ण्यम्", meaning: "वरणीय/श्रेष्ठ" },
      { word: "भर्गः॑", meaning: "पापनाशक दिव्य तेज को" },
      { word: "दे॒वस्य॑", meaning: "देव के" },
      { word: "धी॒म॒हि॒", meaning: "हम ध्यान करते हैं" },
      { word: "धियः॑", meaning: "बुद्धियों को" },
      { word: "यः", meaning: "जो (परमात्मा)" },
      { word: "नः॑", meaning: "हमारी" },
      { word: "प्र॒-चो॒दया॑त्", meaning: "प्रेरित करे" }
    ],
    shastricContext: "वेदों की माता गायत्री महामंत्र। यह बुद्धि की शुद्धि और आत्म-साक्षात्कार का परम वैदिक सूत्र है।",
    orderIndex: 10,
    status: "ACTIVE"
  },
  {
    id: "rv-7-59-12",
    vedaId: "rigveda",
    nodeId: "rv-sukta-7-59",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (महामृत्युंजय मन्त्र)",
    sectionRef: "मण्डल ७, सूक्त ५९",
    mantraNumber: "७.५९.१२",
    rishi: "वसिष्ठ मैत्रावरुणि",
    devata: "रुद्र / त्र्यम्बक",
    chhanda: "अनुष्टुप् (३२ वर्ण)",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ त्र्य॑म्बकं यजामहे सुग॒न्धिं पु॑ष्टि॒वर्ध॑नम्।\nउ॒र्वा॒रु॒कमि॑व॒ बन्ध॑नान्मृ॒त्योर्मु॑क्षीय॒ मामृता॑त्॥१२॥",
    transliteration: "oṃ tryambakaṃ yajāmahe sugandhiṃ puṣṭi-vardhanam |\nurvārukam iva bandhanān mṛtyor mukṣīya māmṛtāt || 12 ||",
    hindiTranslation: "हम त्रिनेत्रधारी, सुगंधित और समस्त जीवन का पोषण करने वाले परमपिता परमात्मा की आराधना करते हैं। जिस प्रकार पका हुआ खरबूजा अपनी बेल से सहज ही मुक्त हो जाता है, उसी प्रकार हम मृत्यु के भय और संसार-बन्धन से मुक्त हों, किन्तु अमरत्व से कभी विलग न हों।",
    englishTranslation: "We worship the Three-Eyed Lord of fragrant auspiciousness who nourishes all beings. As a ripe gourd is freed effortlessly from its vine, may we be liberated from death and worldly bondage, yet never separated from immortality.",
    hinglishTranslation: "Hum tin netro wale sugandhit aur poshan dene wale Bhagwan Rudra ki aradhana karte hain. Jaise kharbuja bel se pak kar aazad hota hai, waise hi hum mrityu ke bandhan se mukt hokar amrit ko prapt karein.",
    padapatha: [
      { word: "त्र्य॑म्बकम्", meaning: "त्रिनेत्रधारी परमात्मा को" },
      { word: "य॒जा॒म॒हे॒", meaning: "हम पूजते हैं" },
      { word: "सु॒-ग॒न्धिम्", meaning: "दिव्य सुगंधि वाले को" },
      { word: "पु॒ष्टि॒-वर्ध॑नम्", meaning: "पोषण को बढ़ाने वाले को" },
      { word: "उ॒र्वा॒रु॒कम्-इ॑व", meaning: "पके हुए खरबूजे के समान" },
      { word: "बन्ध॑नात्", meaning: "डंठल/बन्धन से" },
      { word: "मृ॒त्योः", meaning: "मृत्यु से" },
      { word: "मु॒क्षी॒य॒", meaning: "मुक्त होऊँ" },
      { word: "मा", meaning: "नहीं" },
      { word: "अ॒मृता॑त्", meaning: "अमरता से" }
    ],
    shastricContext: "रोग, अकाल मृत्यु और भव-बंधन से मुक्ति प्रदान करने वाला प्रसिद्ध महामृत्युंजय मंत्र।",
    orderIndex: 12,
    status: "ACTIVE"
  },
  {
    id: "rv-10-90-1",
    vedaId: "rigveda",
    nodeId: "rv-sukta-10-90",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (पुरुष सूक्त)",
    sectionRef: "मण्डल १०, सूक्त ९०",
    mantraNumber: "१०.९०.१",
    rishi: "नारायण",
    devata: "परम पुरुष (Universal Cosmic Being)",
    chhanda: "अनुष्टुप्",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ स॒हस्र॑शीर्षा॒ पुरु॑षः सहस्रा॒क्षः स॒हस्र॑पात्।\nस भूमिं॑ वि॒श्वतो॑ वृ॒त्वात्य॑तिष्ठद्दशाङ्गु॒लम्॥१॥",
    transliteration: "oṃ sahasra-śīrṣā puruṣaḥ sahasrākṣaḥ sahasra-pāt |\nsa bhūmiṃ viśvato vṛtvāty atiṣṭhad daśāṅgulam || 1 ||",
    hindiTranslation: "वह विराट् परम पुरुष सहस्रों (अनंत) सिरों, अनंत नेत्रों और अनंत चरणों वाला है। वह इस संपूर्ण ब्रह्माण्ड को सब ओर से व्याप्त करके भी दस अंगुल ऊपर (ब्रह्माण्ड की सीमा से परे) अवस्थित है।",
    englishTranslation: "The Cosmic Purusha possesses a thousand heads, a thousand eyes, and a thousand feet. Encompassing the entire universe on every side, He transcends it by ten fingers beyond all boundaries.",
    hinglishTranslation: "Wah Virat Param Purush hazaron sir, aankhein aur paanv wala hai. Wah is sampoorna srishti ko charo taraf se gherkar bhi usse pare atirikta sthit hai.",
    padapatha: [
      { word: "स॒हस्र॑-शीर्षा", meaning: "अनंत सिरों वाला" },
      { word: "पुरु॑षः", meaning: "विराट् पुरुष" },
      { word: "स॒ह॒स्र॒-अ॒क्षः", meaning: "अनंत नेत्रों वाला" },
      { word: "स॒हस्र॑-पात्", meaning: "अनंत चरणों वाला" },
      { word: "सः", meaning: "वह" },
      { word: "भूमि॑म्", meaning: "सम्पूर्ण ब्रह्माण्ड को" },
      { word: "वि॒श्वतः॑", meaning: "चारों ओर से" },
      { word: "वृ॒त्वा", meaning: "व्याप्त करके" },
      { word: "अति॑", meaning: "पार होकर" },
      { word: "अ॒ति॒ष्ठ॒त्", meaning: "स्थित है" },
      { word: "द॒श-अ॒ङ्गु॒लम्", meaning: "दस अंगुल परे" }
    ],
    shastricContext: "वेदों का सर्वोच्च दार्शनिक सूक्त। समस्त चर-अचर में एक ही परमात्मा की सर्वव्यापकता का प्रतिपादन।",
    orderIndex: 20,
    status: "ACTIVE"
  },
  {
    id: "rv-10-129-1",
    vedaId: "rigveda",
    nodeId: "rv-sukta-10-129",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (नासदीय सूक्त - ब्रह्माण्ड उत्पत्ति)",
    sectionRef: "मण्डल १०, सूक्त १२९",
    mantraNumber: "१०.१२९.१",
    rishi: "परमेष्ठी प्रजापति",
    devata: "भाववृत्त (Cosmic Origin)",
    chhanda: "त्रिष्टुप् (४४ वर्ण)",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "नासो॒दासी॒न्नो सदा॑सीत्त॒दानीं॒ नासी॒द्रजो॒ नो व्यो॑मा प॒रो यत्।\nकिमाव॑रीवः॒ कुह॒ कस्य॒ शर्म॒न्नम्भः॒ किमा॑सी॒द्गह॑नं गभी॒रम्॥१॥",
    transliteration: "nāsad āsīn no sad āsīt tadānīṃ nāsīd rajo no vyomā paro yat |\nkim āvarīvaḥ kuha kasya śarmann ambhaḥ kim āsīd gahanaṃ gabhīram || 1 ||",
    hindiTranslation: "सृष्टि के आरम्भ से पूर्व न असत् (अस्तित्वहीनता) था और न सत् (दृश्य जगत)। न कोई लोक था और न परे फैला हुआ अंतरिक्ष। तब किसने किसे ढँक रखा था? कहाँ और किसके आश्रय में? क्या वहाँ कोई अगाध अथाह जल था?",
    englishTranslation: "Then was not non-existence nor existence: there was no realm of air, no sky beyond it. What covered it, and where? and what gave shelter? Was water there, unfathomed depth of water?",
    hinglishTranslation: "Srishti ke aarambh se pehle na asat tha na sat. Na antariksh tha na aakash. Tab kisne kisko chhipaya tha? Kya koi agadh gahra jal tha?",
    padapatha: [
      { word: "न", meaning: "नहीं" },
      { word: "अ॒सत्", meaning: "अभाव/अस्तित्वहीन" },
      { word: "आ॒सी॒त्", meaning: "था" },
      { word: "नो", meaning: "न ही" },
      { word: "सत्", meaning: "सत्/पदार्थ" },
      { word: "त॒दानी॑म्", meaning: "उस प्रलयकाल में" },
      { word: "न", meaning: "न" },
      { word: "आ॒सी॒त्", meaning: "था" },
      { word: "रजः॑", meaning: "लोक" },
      { word: "नो", meaning: "न" },
      { word: "व्यो॑म", meaning: "आकाश" },
      { word: "परः॑", meaning: "परे" }
    ],
    shastricContext: "विश्व का महानतम दार्शनिक सृष्टि-सूक्त (Hymn of Creation), जो आधुनिक बिग बैंग सिद्धान्त से भी गहरा आध्यात्मिक विमर्श प्रस्तुत करता है।",
    orderIndex: 25,
    status: "ACTIVE"
  },
  {
    id: "rv-10-191-2",
    vedaId: "rigveda",
    nodeId: "rv-sukta-10-191",
    vedaName: "ऋग्वेद (Rigveda)",
    shakha: "शाकल शाखा",
    textName: "ऋग्वेद संहिता (संज्ञान / संगठन सूक्त)",
    sectionRef: "मण्डल १०, सूक्त १९१",
    mantraNumber: "१०.१९१.२",
    rishi: "संवनन आङ्गिरस",
    devata: "संज्ञान (Universal Harmony)",
    chhanda: "अनुष्टुप्",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "सं ग॑च्छध्वं॒ सं व॑दध्वं॒ सं वो॒ मनां॑सि जानताम्।\nदे॒वा भा॒गं यथा॒ पूर्वे॑ संजाना॒ना उ॒पास॑ते॥२॥",
    transliteration: "saṃ gacchadhvaṃ saṃ vadadhvaṃ saṃ vo manāṃsi jānatām |\ndevā bhāgaṃ yathā pūrve sañjānānā upāsate || 2 ||",
    hindiTranslation: "तुम सब एक साथ मिलकर चलो, एक स्वर में प्रेमपूर्वक बोलो, और तुम्हारे मन एक समान ज्ञान और सद्भाव को प्राप्त करें; जैसे पूर्वकाल के देवगण परस्पर एकमत होकर अपना यज्ञ-भाग ग्रहण करते थे।",
    englishTranslation: "Walk together in harmony, speak together in unity, let your minds comprehend with shared understanding, just as the ancient deities in harmony accepted their sacred portions.",
    hinglishTranslation: "Tum sab saath chalo, ek sath milkar bolo aur tumhare man ek jaise gyan ko jaanein, jaise purvkal ke devta aapas me prem se yagya-bhaag lete the.",
    padapatha: [
      { word: "सम्", meaning: "एक साथ" },
      { word: "ग॒च्छ॒ध्व॒म्", meaning: "चलो/आगे बढ़ो" },
      { word: "सम्", meaning: "एक साथ" },
      { word: "व॒द॒ध्व॒म्", meaning: "बोलो/विचार करो" },
      { word: "सम्", meaning: "समान रूप से" },
      { word: "वः॒", meaning: "तुम्हारे" },
      { word: "मनां॑सि", meaning: "मन" },
      { word: "जा॒न॒ता॒म्", meaning: "समझें/ज्ञानवान हों" }
    ],
    shastricContext: "ऋग्वेद का अंतिम अमर सन्देश। विश्व-शान्ति, सामाजिक एकता और सद्भाव का मूल वैदिक सूत्र।",
    orderIndex: 30,
    status: "ACTIVE"
  },

  // =========================================================================
  // YAJURVEDA MANTRAS (vedicheritage.gov.in Shukla & Krishna Samhitas)
  // =========================================================================
  {
    id: "yj-1-1",
    vedaId: "yajurveda",
    nodeId: "yj-adhyaya-1",
    vedaName: "यजुर्वेद (Yajurveda)",
    shakha: "वाजसनेयि माध्यन्दिन शाखा",
    textName: "वाजसनेयि संहिता (दर्शपूर्णमास)",
    sectionRef: "अध्याय १, मन्त्र १",
    mantraNumber: "१.१",
    rishi: "परमेष्ठी प्रजापति",
    devata: "यज्ञ / वायु",
    chhanda: "यजुः (गद्यात्मक)",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ इ॒षे त्वो॒र्जे त्वा॑ वा॒यव॑ स्थ दे॒वो वः॑ सवि॒ता प्रार्प॑यतु॒ श्रेष्ठ॑तमाय॒ कर्म॑णे॥१॥",
    transliteration: "oṃ iṣe tvorje tvā vāyava stha devo vaḥ savitā prārpayatu śreṣṭhatamāya karmaṇe || 1 ||",
    hindiTranslation: "हे पलाश की शाखा! हम तुम्हें अन्नादि की समृद्धि और प्राण-ऊर्जा की वृद्धि के लिए ग्रहण करते हैं। हे बछड़ों! तुम वायु के समान गतिशील बनो। सविता देव तुम्हें श्रेष्ठतम यज्ञ-कर्म के लिए प्रेरित करें।",
    englishTranslation: "For food and vigor we take thee; O calves, be swift as the wind. May the divine inspirer Savitr impel you all unto the highest and most sacred action.",
    hinglishTranslation: "Anna aur urja ki vriddhi ke liye hum tumhe grahan karte hain. Hey vatsa, tum vayu jaise gatiwan bano. Savita Dev tumhe sarvashreshtha karma ke liye prerit karein.",
    padapatha: [
      { word: "इ॒षे", meaning: "अन्न/समृद्धि के लिए" },
      { word: "त्वा॑", meaning: "तुझे" },
      { word: "ऊ॒र्जे", meaning: "प्राण-शक्ति/ऊर्जा के लिए" },
      { word: "त्वा॑", meaning: "तुझे" },
      { word: "वा॒यवः॑", meaning: "वायु के समान" },
      { word: "स्थ॒", meaning: "होओ" },
      { word: "दे॒वः", meaning: "दिव्य" },
      { word: "स॒वि॒ता", meaning: "सविता परमात्मा" },
      { word: "प्र", meaning: "उत्कृष्ट रूप से" },
      { word: "अ॒र्प॒य॒तु॒", meaning: "प्रेरित करे" },
      { word: "श्रेष्ठ॑तमाय", meaning: "सर्वोत्तम" },
      { word: "कर्म॑णे", meaning: "यज्ञ कर्म के लिए" }
    ],
    shastricContext: "यजुर्वेद का प्रथम महामंत्र। यह कर्म की महत्ता और यज्ञ को संसार का 'श्रेष्ठतम कर्म' घोषित करता है।",
    orderIndex: 1,
    status: "ACTIVE"
  },
  {
    id: "yj-16-1",
    vedaId: "yajurveda",
    nodeId: "yj-adhyaya-16",
    vedaName: "यजुर्वेद (Yajurveda)",
    shakha: "वाजसनेयि माध्यन्दिन",
    textName: "वाजसनेयि संहिता (शतरुद्रीय - श्रीरुद्रम्)",
    sectionRef: "अध्याय १६, मन्त्र १",
    mantraNumber: "१६.१",
    rishi: "परमेष्ठी प्रजापति",
    devata: "रुद्र (Rudra)",
    chhanda: "पंक्ति (४० वर्ण)",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ नम॑स्ते रुद्र म॒न्यव॑ उ॒तो त॒ इष॑वे॒ नमः॑।\nबा॒हुभ्या॑मु॒त ते॒ नमः॑॥१॥",
    transliteration: "oṃ namas te rudra manyava uto ta iṣave namaḥ |\nbāhubhyām uta te namaḥ || 1 ||",
    hindiTranslation: "हे रुद्र! आपके क्रोध को हमारा नमन है। आपके बाण को हमारा नमन है और आपकी दोनों भुजाओं को हमारा सादर नमन है।",
    englishTranslation: "O Rudra, homage be to your wrath, and homage be unto your arrow. Homage be to both of your mighty arms.",
    hinglishTranslation: "Hey Bhagwan Rudra, aapke krodh ko pranam, aapke baan ko pranam aur aapki dono bhujaon ko hamara barambar pranam.",
    padapatha: [
      { word: "नमः॑", meaning: "नमस्कार" },
      { word: "ते॒", meaning: "आपके" },
      { word: "रु॒द्र॒", meaning: "हे दुःखों के विनाशक रुद्र" },
      { word: "म॒न्यवे॑", meaning: "क्रोध को" },
      { word: "उ॒तो", meaning: "और भी" },
      { word: "ते॒", meaning: "आपके" },
      { word: "इष॑वे", meaning: "बाण को" },
      { word: "नमः॑", meaning: "प्रणाम" },
      { word: "बा॒हुभ्या॑म्", meaning: "दोनों भुजाओं को" },
      { word: "उ॒त", meaning: "और" },
      { word: "ते॒", meaning: "आपके" },
      { word: "नमः॑", meaning: "नमस्कार" }
    ],
    shastricContext: "रुद्राष्टाध्यायी (नमकम्) का प्रसिद्ध आरम्भिक मंत्र। संहारक शक्ति को शांत और मंगलकारी बनाने की प्रार्थना।",
    orderIndex: 5,
    status: "ACTIVE"
  },
  {
    id: "yj-34-1",
    vedaId: "yajurveda",
    nodeId: "yj-adhyaya-34",
    vedaName: "यजुर्वेद (Yajurveda)",
    shakha: "वाजसनेयि माध्यन्दिन",
    textName: "वाजसनेयि संहिता (शिवसंकल्प सूक्त)",
    sectionRef: "अध्याय ३४, मन्त्र १",
    mantraNumber: "३४.१",
    rishi: "शिवसंकल्प",
    devata: "मन (Pure Divine Mind)",
    chhanda: "त्रिष्टुप्",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ यज्जाग्र॑तो दू॒रमुदै॑ति॒ दैवं॒ तदु॑ सु॒प्तस्य॒ तथैवेति॑।\nदू॒रं॒ग॒मं ज्योति॑षां॒ ज्योति॒रेकं॒ तन्मे॒ मनः॑ शि॒वस॑ङ्क॒ल्पम॑स्तु॥१॥",
    transliteration: "oṃ yaj jāgrato dūram udaiti daivaṃ tad u suptasya tathaivaiti |\ndūraṅ-gamaṃ jyotiṣāṃ jyotir ekaṃ tan me manaḥ śiva-saṅkalpam astu || 1 ||",
    hindiTranslation: "जागते हुए मनुष्य का जो दिव्य मन दूर-दूर तक विचरण करता है और सोते हुए भी उसी प्रकार सुदूर चला जाता है; जो समस्त इन्द्रिय-ज्योतियों की एकमात्र मूल ज्योति है—वह मेरा मन सदा कल्याणकारी और पवित्र संकल्पों से युक्त बने।",
    englishTranslation: "That divine mind which wanders far away when awake, and likewise in deep sleep; that far-traveling light of all lights—may that mind of mine be filled with auspicious, noble resolve.",
    hinglishTranslation: "Jaagte hue jo man door-door tak daudta hai aur sote hue bhi waisa hi karta hai; jo sabhi indriyon ki akeli jyoti hai—mera wah man shubh sankalpo wala bane.",
    padapatha: [
      { word: "यत्", meaning: "जो" },
      { word: "जाग्र॑तः", meaning: "जागते हुए का" },
      { word: "दू॒रम्", meaning: "दूर" },
      { word: "उदै॑ति", meaning: "जाता है" },
      { word: "दैव॑म्", meaning: "दिव्य शक्ति युक्त" },
      { word: "तन्मे॑", meaning: "वह मेरा" },
      { word: "मनः॑", meaning: "मन" },
      { word: "शि॒व-स॑ङ्क॒ल्पम्", meaning: "कल्याणकारी संकल्प वाला" },
      { word: "अ॒स्तु॒", meaning: "होवे" }
    ],
    shastricContext: "वैदिक मनोविज्ञान का अमर मंत्र। मनुष्य के विचारों को सदा सकारात्मक और पवित्र रखने की प्रार्थना।",
    orderIndex: 10,
    status: "ACTIVE"
  },
  {
    id: "yj-36-17",
    vedaId: "yajurveda",
    nodeId: "yj-adhyaya-36",
    vedaName: "यजुर्वेद (Yajurveda)",
    shakha: "वाजसनेयि माध्यन्दिन",
    textName: "वाजसनेयि संहिता (विश्व शान्ति पाठ)",
    sectionRef: "अध्याय ३६, मन्त्र १७",
    mantraNumber: "३६.१७",
    rishi: "प्रजापति",
    devata: "विश्वेदेवाः / विश्व शान्ति",
    chhanda: "निचृद् भुरिगनुष्टुप्",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ द्यौः शान्ति॑र॒न्तरि॑क्षं॒ शान्तिः॑ पृथि॒वी शान्ति॒रापः॒ शान्ति॒रोष॑धयः॒ शान्तिः॑।\nवन॒स्पत॑यः॒ शान्ति॒र्विश्वे॑ दे॒वाः शान्ति॒र्ब्रह्म॒ शान्तिः॒ सर्वं॒ शान्तिः॒ शान्ति॑रेव॒ शान्तिः॒ सा मा॒ शान्ति॑रेधि॥",
    transliteration: "oṃ dyauḥ śāntir antarikṣaṃ śāntiḥ pṛthivī śāntir āpaḥ śāntir oṣadhayaḥ śāntiḥ |\nvanaspatayaḥ śāntir viśve devāḥ śāntir brahma śāntiḥ sarvaṃ śāntiḥ śāntir eva śāntiḥ sā mā śāntir edhi ||",
    hindiTranslation: "द्युलोक शांत हो, अंतरिक्ष शांत हो, पृथ्वी शांत हो, जल शांत हो, ओषधियाँ शांत हों, वनस्पतियाँ शांत हों, समस्त देवगण शांत हों, परब्रह्म शांत हो, संपूर्ण विश्व शांत हो; शांति ही चारों ओर शांत हो, और वह दिव्य शांति मुझमें भी प्रतिष्ठित हो।",
    englishTranslation: "May peace radiate in the celestial realms, in the intermediate space, upon the earth, within the waters, among medicinal herbs, and in the trees. May peace reside in all deities, in the supreme Brahman, and everywhere. May pure peace prevail, and may that supreme peace enter into me.",
    hinglishTranslation: "Aakash me shanti ho, antariksh me shanti ho, prithvi par shanti ho, jal aur aushadhiyon me shanti ho. Sabhi devtao me aur Brahma me shanti ho. Charo taraf shanti hi shanti ho aur wah shanti mujhe prapt ho.",
    padapatha: [
      { word: "द्यौः", meaning: "द्युलोक/स्वर्ग" },
      { word: "शान्तिः॑", meaning: "शान्तिदायक हो" },
      { word: "अ॒न्तरि॑क्षम्", meaning: "अंतरिक्ष" },
      { word: "शान्तिः॑", meaning: "शांत हो" },
      { word: "पृ॒थि॒वी", meaning: "धरती" },
      { word: "शान्तिः॑", meaning: "शांत हो" },
      { word: "आपः॑", meaning: "जल" },
      { word: "शान्तिः॑", meaning: "शांत हो" },
      { word: "ओष॑धयः", meaning: "औषधियाँ" },
      { word: "वन॒स्पत॑यः", meaning: "वृक्ष-वनस्पतियाँ" },
      { word: "ब्रह्म॑", meaning: "परब्रह्म" },
      { word: "सर्व॑म्", meaning: "समस्त सृष्टि" }
    ],
    shastricContext: "सनातन वैदिक संस्कृति का सार्वभौमिक शांति पाठ। पर्यावरण और संपूर्ण चराचर के संतुलन का संदेश।",
    orderIndex: 15,
    status: "ACTIVE"
  },
  {
    id: "yj-40-1",
    vedaId: "yajurveda",
    nodeId: "yj-adhyaya-40",
    vedaName: "यजुर्वेद (Yajurveda)",
    shakha: "वाजसनेयि माध्यन्दिन",
    textName: "ईशावास्योपनिषद् (वाजसनेयि संहिता ४०वां अध्याय)",
    sectionRef: "अध्याय ४०, मन्त्र १",
    mantraNumber: "४०.१",
    rishi: "दध्यङ् आथर्वण",
    devata: "ईश्वर / आत्मतत्त्व",
    chhanda: "अनुष्टुप्",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "ॐ ई॒शा वा॒स्य॑मि॒दं सर्वं॒ यत्किञ्च॒ जग॑त्यां॒ जग॑त्।\nतेन॑ त्य॒क्तेन॑ भुञ्जीथा॒ मा गृ॑धः॒ कस्य॑ स्वि॒द्धन॑म्॥१॥",
    transliteration: "oṃ īśā vāsyam idaṃ sarvaṃ yat kiñca jagatyāṃ jagat |\ntena tyaktena bhuñjīthā mā gṛdhaḥ kasya svid dhanam || 1 ||",
    hindiTranslation: "इस गतिशील संसार में जो कुछ भी जड़-चेतन जगत है, वह सब ईश्वर से व्याप्त है। अतः त्यागभाव से उसका भोग करो; किसी के धन-ऐश्वर्य का लोभ मत करो।",
    englishTranslation: "All this, whatever moves in this moving world, is enveloped and indwelt by the Divine Lord. Therefore enjoy through renunciation; covet not the wealth of anyone.",
    hinglishTranslation: "Is poore jagat me jo kuch bhi hai, sabme Ishwar vyapt hai. Isliye tyagbhav se upbhog karo, kisi ke dhan ka lalach mat karo.",
    padapatha: [
      { word: "ई॒शा", meaning: "ईश्वर से" },
      { word: "वा॒स्य॑म्", meaning: "आच्छादित/व्याप्त" },
      { word: "इ॒दम्", meaning: "यह" },
      { word: "सर्व॑म्", meaning: "सब कुछ" },
      { word: "यत्", meaning: "जो" },
      { word: "किञ्च॑", meaning: "कुछ भी" },
      { word: "जग॑त्याम्", meaning: "संसार में" },
      { word: "जग॑त्", meaning: "जगत" },
      { word: "तेन॑", meaning: "उसके द्वारा" },
      { word: "त्य॒क्तेन॑", meaning: "त्यागपूर्वक" },
      { word: "भु॒ञ्जी॒थाः॒", meaning: "भोग करो" },
      { word: "मा", meaning: "मत" },
      { word: "गृ॒धः॒", meaning: "लोभ करो" }
    ],
    shastricContext: "उपनिषदों का शिरोमणि मंत्र। महात्मा गांधी ने कहा था कि यदि सब शास्त्र नष्ट हो जाएँ और केवल यह एक मंत्र बचे, तो भी सनातन धर्म अक्षुण्ण रहेगा।",
    orderIndex: 20,
    status: "ACTIVE"
  },
  {
    id: "yj-kr-1-1",
    vedaId: "yajurveda",
    nodeId: "taittiriya-upanishad",
    vedaName: "यजुर्वेद (कृष्ण यजुर्वेद)",
    shakha: "तैत्तिरीय शाखा",
    textName: "तैत्तिरीय उपनिषद् (शिक्षावल्ली)",
    sectionRef: "शिक्षावल्ली, अनुवाक ११",
    mantraNumber: "१.११.१",
    rishi: "त्रिशङ्कु",
    devata: "धर्म एवं सत्य",
    chhanda: "यजुः सूत्र",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "स॒त्यं व॑द। ध॒र्मं च॑र। स्वा॒ध्या॒यान्मा प्र॑मदः। आ॒चा॒र्या॑य प्रि॒यं धन॒माहृ॑त्य प्र॒जात॑न्तुं मा व्य॑वच्छेत्सीः॥",
    transliteration: "satyaṃ vada | dharmaṃ cara | svādhyāyān mā pramadaḥ | ācāryāya priyaṃ dhanam āhṛtya prajā-tantuṃ mā vyavacchetsīḥ ||",
    hindiTranslation: "सदा सत्य बोलो। धर्म का आचरण करो। स्वाध्याय (आत्म-अध्ययन) में कभी प्रमाद मत करो। आचार्य को प्रिय दक्षिणा भेंट कर गृहस्थाश्रम में संतान-परम्परा को मत तोड़ो।",
    englishTranslation: "Speak the truth. Walk the path of righteousness. Neglect not sacred self-study. Offer dear treasures unto the preceptor and sever not the lineage of righteous progeny.",
    hinglishTranslation: "Satya bolo. Dharma ka aacharan karo. Swadhyay me alasya mat karo. Guru ko dakshina dekar vansha-parampara ko aage badhao.",
    padapatha: [
      { word: "स॒त्यम्", meaning: "सत्य को" },
      { word: "व॒द॒", meaning: "बोलो" },
      { word: "ध॒र्मम्", meaning: "धर्म का" },
      { word: "च॒र॒", meaning: "आचरण करो" },
      { word: "स्वा॒ध्या॒यात्", meaning: "स्वाध्याय से" },
      { word: "मा", meaning: "मत" },
      { word: "प्र॒म॒दः॒", meaning: "प्रमाद/आलस्य करो" }
    ],
    shastricContext: "प्राचीन भारतीय गुरुकुलों का अमर दीक्षांत उपदेश (Convocation Address)।",
    orderIndex: 25,
    status: "ACTIVE"
  },

  // =========================================================================
  // SAMAVEDA MANTRAS (vedicheritage.gov.in Kauthuma & Jaiminiya Samhita)
  // =========================================================================
  {
    id: "sv-1-1-1",
    vedaId: "samaveda",
    nodeId: "sv-agneya-kanda",
    vedaName: "सामवेद (Samaveda)",
    shakha: "कौथुम शाखा",
    textName: "सामवेद संहिता (पूर्वार्चिक - आग्नेय काण्ड)",
    sectionRef: "पूर्वार्चिक, प्रपाठक १, दशति १",
    mantraNumber: "१.१.१",
    rishi: "भरद्वाज बार्हस्पत्य",
    devata: "अग्नि (गान रूप)",
    chhanda: "गायत्री (८+८+८)",
    svara: "सामगान स्वर (सप्त स्वर युक्त)",
    sanskrit: "ॐ अग्न॒ आ या॑हि वी॒तये॑ गृणा॒नो ह॒व्यदा॑तये।\nनि होता॑ सत्सि ब॒र्हिषि॑॥१॥",
    transliteration: "oṃ agna ā yāhi vītaye gṛṇāno havyadātaye |\nni hotā satsi barhiṣi || 1 ||",
    hindiTranslation: "हे प्रकाशवान अग्निदेव! हमारी स्तुतियों द्वारा प्रशंसित होकर, हव्य (आहुति) को ग्रहण करने तथा देवों को प्रदान करने के लिए पधारिए। और इस पवित्र दर्भासन (बर्हि) पर होता रूप में विराजमान होइए।",
    englishTranslation: "O radiant Agni, invited by our songs, come hither to partake of the oblation and to bestow divine gifts. Sit down as the chief summoner upon the sacred grass.",
    hinglishTranslation: "Hey Agni Dev, hamari stutiyo se prasanna hokar yagya me aahuti grahan karne aaiye aur kusha ke aasan par virajman hoiye.",
    padapatha: [
      { word: "अग्ने॑", meaning: "हे अग्निदेव" },
      { word: "आ", meaning: "आइए" },
      { word: "या॒हि॒", meaning: "पधारिए" },
      { word: "वी॒तये॑", meaning: "हव्य ग्रहण करने के लिए" },
      { word: "गृ॒णा॒नः", meaning: "स्तुति किए जाते हुए" },
      { word: "ह॒व्य-दा॑तये", meaning: "हव्य देने के लिए" },
      { word: "नि", meaning: "निश्चयपूर्वक" },
      { word: "होता॑", meaning: "होता के रूप में" },
      { word: "स॒त्सि॒", meaning: "बैठिए" },
      { word: "ब॒र्हिषि॑", meaning: "पवित्र कुशासन पर" }
    ],
    shastricContext: "सामवेद का सर्वप्रथम आदि मंत्र। इसे सामगान की मधुर ध्वनि में गाया जाता है जिससे अंतःकरण शुद्ध होता है।",
    orderIndex: 1,
    status: "ACTIVE"
  },
  {
    id: "sv-1-1-2",
    vedaId: "samaveda",
    nodeId: "sv-agneya-kanda",
    vedaName: "सामवेद (Samaveda)",
    shakha: "कौथुम शाखा",
    textName: "सामवेद संहिता (पूर्वार्चिक)",
    sectionRef: "पूर्वार्चिक, प्रपाठक १, दशति १",
    mantraNumber: "१.१.२",
    rishi: "मेधातिथि काण्व",
    devata: "अग्नि",
    chhanda: "गायत्री",
    svara: "सामगान स्वर",
    sanskrit: "त्वम॑ग्ने य॒ज्ञानां॒ होता॒ विश्वा॑षां हि॒तः।\nदे॒वेभि॒र्मानु॑षे॒ जने॑॥२॥",
    transliteration: "tvam agne yajñānāṃ hotā viśvāsāṃ hitaḥ |\ndevebhir mānuṣe jane || 2 ||",
    hindiTranslation: "हे अग्नि! आप सभी यज्ञों के प्रधान आह्वानकर्ता (होता) हैं। समस्त मानव जाति के मध्य देवताओं द्वारा आप ही परम हितैषी के रूप में स्थापित किए गए हैं।",
    englishTranslation: "You, O Agni, are the chief priest of all sacrifices, established by the divine celestials as the foremost benefactor among human beings.",
    hinglishTranslation: "Hey Agni, aap sabhi yagyo ke mukhiya hain. Devtao ne manushyo ke kalyan ke liye aapko hi sabse bada hitkari banaya hai.",
    padapatha: [
      { word: "त्वम्", meaning: "आप" },
      { word: "अग्ने॑", meaning: "हे अग्नि" },
      { word: "य॒ज्ञाना॑म्", meaning: "यज्ञों के" },
      { word: "होता॑", meaning: "होता/आह्वानकर्ता" },
      { word: "विश्वा॑षाम्", meaning: "समस्त के" },
      { word: "हि॒तः", meaning: "हितकारी" },
      { word: "दे॒वेभिः॑", meaning: "देवताओं द्वारा" },
      { word: "मानु॑षे", meaning: "मानव" },
      { word: "जने॑", meaning: "समाज में" }
    ],
    shastricContext: "अग्नि को मानव और देवों के बीच दिव्य दूत तथा सेतु के रूप में प्रतिष्ठित करता है।",
    orderIndex: 2,
    status: "ACTIVE"
  },
  {
    id: "sv-1-2-1",
    vedaId: "samaveda",
    nodeId: "sv-aindra-parva",
    vedaName: "सामवेद (Samaveda)",
    shakha: "कौथुम शाखा",
    textName: "सामवेद संहिता (ऐन्द्र पर्व)",
    sectionRef: "पूर्वार्चिक, प्रपाठक २, ऐन्द्र पर्व",
    mantraNumber: "१.२.१",
    rishi: "मधुच्छन्दा वैश्वामित्र",
    devata: "इन्द्र (Indra)",
    chhanda: "गायत्री",
    svara: "सामगान स्वर",
    sanskrit: "इन्द्र॒मिद्गा॒थिनो॑ बृ॒हदिन्द्र॑म॒र्केभि॑र॒र्किनः॑।\nइन्द्रं॒ वाणी॑रनूषत॥",
    transliteration: "indram id gāthino bṛhad indram arkebhir arkinaḥ |\nindraṃ vāṇīr anūṣata ||",
    hindiTranslation: "सामगान करने वाले गायक श्रेष्ठ सामगीतों द्वारा इन्द्रदेव की ही महिमा गाते हैं, ऋचाओं के ज्ञाता ऋक-मंत्रों से उन्हीं की स्तुति करते हैं, और विविध वैदिक वाणी उन्हीं का यशोगान करती है।",
    englishTranslation: "Singers of holy song praise Indra alone with lofty melodies; chanters of praise laud Him with sacred verses, and all divine hymns magnify Indra's glory.",
    hinglishTranslation: "Samaveda gane wale gayak geeto se Indra ki stuti karte hain, rishigan mantro se unka gungan karte hain aur pavitra vani unka yash gati hai.",
    padapatha: [
      { word: "इन्द्र॑म्", meaning: "इन्द्रदेव को" },
      { word: "इत्", meaning: "ही" },
      { word: "गा॒थिनः॑", meaning: "सामगायक" },
      { word: "बृ॒हत्", meaning: "महान् गान से" },
      { word: "अ॒र्केभिः॑", meaning: "ऋचाओं द्वारा" },
      { word: "अ॒र्किनः॑", meaning: "स्तोतागण" },
      { word: "वाणीः॑", meaning: "वेदवाणियाँ" },
      { word: "अ॒नू॒ष॒त॒", meaning: "गान करती हैं" }
    ],
    shastricContext: "सामवेद में संगीत, स्वर और वाणी के समन्वय से परमात्मा की शक्ति (इन्द्र) के स्तुति-गान का प्रामाणिक रूप।",
    orderIndex: 5,
    status: "ACTIVE"
  },
  {
    id: "sv-2-1-1",
    vedaId: "samaveda",
    nodeId: "sv-pavamana-kanda",
    vedaName: "सामवेद (Samaveda)",
    shakha: "कौथुम शाखा",
    textName: "सामवेद संहिता (पवमान काण्ड)",
    sectionRef: "पूर्वार्चिक, प्रपाठक ५, पवमान",
    mantraNumber: "२.१.१",
    rishi: "ऋषि असित देवल",
    devata: "पवमान सोम (Divine Nectar)",
    chhanda: "गायत्री",
    svara: "सामगान स्वर",
    sanskrit: "उ॒च्चा ते॑ जा॒तमन्ध॑सो दि॒वि सद्भूम्या॑ ददे।\nउ॒ग्रं शर्म॑ म॒हि श्रवः॑॥",
    transliteration: "uccā te jātam andhaso divi sad bhūmyā dade |\nugraṃ śarma mahi śravaḥ ||",
    hindiTranslation: "हे पवमान सोम! द्युलोक में उत्पन्न आपका पावन रस पृथ्वी पर प्राप्त होता है। वह साधक को अभेद्य दिव्य रक्षा और महान् यश प्रदान करने वाला है।",
    englishTranslation: "High-born is the pure juice of thy Soma; dwelling in heaven, it is received upon the earth, conferring formidable protection and glorious renown.",
    hinglishTranslation: "Hey pavitra Som ras! Swarg me utpanna aapka divya ras dharti par milta hai jo sadhak ko atoot suraksha aur yash deta hai.",
    padapatha: [
      { word: "उ॒च्चा", meaning: "उच्च लोक में" },
      { word: "ते॒", meaning: "तेरा" },
      { word: "जा॒तम्", meaning: "उत्पन्न" },
      { word: "अन्ध॑सः", meaning: "सोम रस का" },
      { word: "दि॒वि", meaning: "द्युलोक में" },
      { word: "भू॒म्या॑", meaning: "भूमि पर" },
      { word: "शर्म॑", meaning: "कल्याण/रक्षा" },
      { word: "श्रवः॑", meaning: "कीर्ति" }
    ],
    shastricContext: "पवमान सोम का शुद्धिकारी प्रभाव। चेतना के ऊर्ध्वगमन और अमृत-रस की प्राप्ति का प्रतीक।",
    orderIndex: 10,
    status: "ACTIVE"
  },
  {
    id: "sv-ch-1-1",
    vedaId: "samaveda",
    nodeId: "chandogya-upanishad",
    vedaName: "सामवेद (कौथुम शाखा)",
    shakha: "कौथुम शाखा",
    textName: "छान्दोग्य उपनिषद् (उद्गीथ उपासना)",
    sectionRef: "अध्याय १, खण्ड १, मन्त्र १",
    mantraNumber: "१.१.१",
    rishi: "उद्दालक आरुणि",
    devata: "ॐकार / उद्गीथ",
    chhanda: "उपनिषद् सूत्र",
    svara: "सामगान स्वर",
    sanskrit: "ॐ इत्ये॒तद॒क्षर॒मुद्गी॑थमुपासीत। ओमिति॒ ह्युद्गा॑यति॒ तस्योप॒व्याख्या॑नम्॥१॥",
    transliteration: "oṃ ity etad akṣaram udgītham upāsīta | om iti hy udgāyati tasyopavyākhyānam || 1 ||",
    hindiTranslation: "'ॐ'—इस अविनाशी एकाक्षर ब्रह्म (उद्गीथ) की उपासना करनी चाहिए। क्योंकि सामगायक 'ॐ' का उच्चारण करके ही सामगान का आरम्भ करता है। यहाँ इसी का गहन आध्यात्मिक निरूपण किया जाता है।",
    englishTranslation: "One should meditate upon the syllable 'OM' as the Udgitha; for chanting begins with 'OM'. Herewith begins its profound explanation.",
    hinglishTranslation: "'OM' is avinashi akshar (Udgitha) ki upasana karni chahiye. Samaveda ke gayak OM bolkar hi gayan shuru karte hain.",
    padapatha: [
      { word: "ॐ", meaning: "प्रणव ॐकार" },
      { word: "इति॑", meaning: "इस प्रकार" },
      { word: "ए॒तत्", meaning: "इस" },
      { word: "अ॒क्षर॑म्", meaning: "अविनाशी अक्षर को" },
      { word: "उद्गी॑थम्", meaning: "उद्गीथ" },
      { word: "उ॒पा॒सी॒त॒", meaning: "उपासना करे" }
    ],
    shastricContext: "सामवेदीय छान्दोग्योपनिषद् का प्रथम मंगलाचरण। नादब्रह्म और ॐकार की सर्वोच्च सत्ता का प्रतिपादन।",
    orderIndex: 15,
    status: "ACTIVE"
  },

  // =========================================================================
  // ATHARVAVEDA MANTRAS (vedicheritage.gov.in Shaunaka Samhita)
  // =========================================================================
  {
    id: "av-1-1-1",
    vedaId: "atharvaveda",
    nodeId: "av-kanda-1-sukta-1",
    vedaName: "अथर्ववेद (Atharvaveda)",
    shakha: "शौनक शाखा",
    textName: "अथर्ववेद संहिता (मेधाजनन सूक्त)",
    sectionRef: "काण्ड १, सूक्त १",
    mantraNumber: "१.१.१",
    rishi: "अथर्वा",
    devata: "वाचस्पति (Lord of Speech & Intellect)",
    chhanda: "अनुष्टुप्",
    svara: "सस्वर वैदिक पाठ (अथर्व स्वर)",
    sanskrit: "ॐ ये त्रि॒षप्ताः॑ परि॒यन्ति॒ विश्वा॑ रू॒पाणि॒ बिभ्र॑तः।\nवा॒चस्पति॒र्बला॒ तेषां॑ त॒न्वो३ अ॒द्य द॑धातु मे॥१॥",
    transliteration: "oṃ ye triṣaptāḥ pariyanti viśvā rūpāṇi bibhrataḥ |\nvācaspatir balā teṣāṃ tanvo adya dadhātu me || 1 ||",
    hindiTranslation: "जो इक्कीस (त्रिषप्त: ३×७ = २१ तत्त्व—५ ज्ञानेन्द्रियाँ, ५ कर्मेन्द्रियाँ, ५ तन्मात्राएँ, ५ महाभूत और १ मन) समस्त रूपों को धारण करते हुए सृष्टि में विचरण करते हैं; वाणी और ज्ञान के स्वामी परमात्मा (वाचस्पति) आज उनके बल और तेज को मेरे शरीर व बुद्धि में स्थापित करें।",
    englishTranslation: "The thrice-seven elements who move everywhere bearing all cosmic forms; may the Lord of Speech and Intellect (Vachaspati) establish their supreme vigor and brilliance within me today.",
    hinglishTranslation: "Jo 21 tatva (tri-sapta) srishti ke sabhi roopo ko dharan karke ghumte hain; gyan ke swami Vachaspati unka tej aur bal aaj mere sharir aur buddhi me sthapit karein.",
    padapatha: [
      { word: "ये", meaning: "जो" },
      { word: "त्रि॒-स॒प्ताः॑", meaning: "इक्कीस दिव्य तत्त्व" },
      { word: "प॒रि॒-यन्ति॑", meaning: "सर्वत्र विचरण करते हैं" },
      { word: "विश्वा॑", meaning: "समस्त" },
      { word: "रू॒पाणि॑", meaning: "रूपों को" },
      { word: "बिभ्र॑तः", meaning: "धारण करते हुए" },
      { word: "वा॒चः-प॑तिः", meaning: "वाणी के स्वामी" },
      { word: "बला॑", meaning: "बल" },
      { word: "तेषा॑म्", meaning: "उनका" },
      { word: "मे॒", meaning: "मुझमें" },
      { word: "द॒धा॒तु॒", meaning: "स्थापित करें" }
    ],
    shastricContext: "अथर्ववेद का प्रथम मंगलाचरण मंत्र। मेधा, स्मरण-शक्ति और आत्म-ज्ञान के जागरण की प्रार्थना।",
    orderIndex: 1,
    status: "ACTIVE"
  },
  {
    id: "av-1-1-2",
    vedaId: "atharvaveda",
    nodeId: "av-kanda-1-sukta-1",
    vedaName: "अथर्ववेद (Atharvaveda)",
    shakha: "शौनक शाखा",
    textName: "अथर्ववेद संहिता (मेधाजनन सूक्त)",
    sectionRef: "काण्ड १, सूक्त १",
    mantraNumber: "१.१.२",
    rishi: "अथर्वा",
    devata: "वाचस्पति",
    chhanda: "अनुष्टुप्",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "पुन॑रेहि वाचस्पते दे॒वेन॒ मन॑सा स॒ह।\nवसो॑ष्पते॒ नि र॑मय॒ मय्ये॒वास्तु॒ मयि॑ श्रु॒तम्॥२॥",
    transliteration: "punar ehi vācaspate devena manasā saha |\nvasoṣpate ni ramaya mayy evāstu mayi śrutam || 2 ||",
    hindiTranslation: "हे वाणी के अधिपति वाचस्पति! दिव्य ज्ञानयुक्त मन के साथ मेरे पास पुनः आइए। हे समस्त वसुओं के पालक! उस ज्ञान को मेरे भीतर स्थिर कीजिए, और जो कुछ मैंने वेदों से सुना है, वह सदा मेरे भीतर प्रतिष्ठित रहे।",
    englishTranslation: "Come again, O Lord of Sacred Speech, together with divine contemplation! O Guardian of Wealth, anchor that sacred wisdom firmly within me, and let all sacred knowledge I have heard abide in me forever.",
    hinglishTranslation: "Hey Vani ke swami Vachaspati, divya man ke sath mere paas punah aaiye. Jo vedik gyan maine suna hai, use hamesha ke liye mere hriday me sthir kar dijiye.",
    padapatha: [
      { word: "पुनः॑", meaning: "पुनः" },
      { word: "आ", meaning: "यहाँ" },
      { word: "इ॒हि॒", meaning: "आइए" },
      { word: "वा॒चः-प॑ते", meaning: "हे वाणी के स्वामी" },
      { word: "दे॒वेन॑", meaning: "दिव्य" },
      { word: "मन॑सा", meaning: "मन के" },
      { word: "स॒ह", meaning: "साथ" },
      { word: "नि", meaning: "निश्चयपूर्वक" },
      { word: "र॒म॒य॒", meaning: "स्थिर कीजिए" },
      { word: "मयि॑", meaning: "मुझमें" },
      { word: "श्रु॒तम्", meaning: "सुना हुआ ज्ञान" }
    ],
    shastricContext: "वैदिक विद्या के स्थायी स्मरण (Retention of Vedic Wisdom) की परम प्रार्थना।",
    orderIndex: 2,
    status: "ACTIVE"
  },
  {
    id: "av-12-1-1",
    vedaId: "atharvaveda",
    nodeId: "av-kanda-12-bhumi",
    vedaName: "अथर्ववेद (Atharvaveda)",
    shakha: "शौनक शाखा",
    textName: "अथर्ववेद संहिता (पृथ्वी / भूमि सूक्त)",
    sectionRef: "काण्ड १२, सूक्त १",
    mantraNumber: "१२.१.१",
    rishi: "अथर्वा",
    devata: "भूमि (Mother Earth)",
    chhanda: "त्रिष्टुप् (४४ वर्ण)",
    svara: "सस्वर वैदिक पाठ",
    sanskrit: "स॒त्यं बृ॒हदृ॒तमु॒ग्रं दी॒क्षा तपो॒ ब्रह्म॑ य॒ज्ञः पृ॑थि॒वीं धा॑रयन्ति।\nसा नो॑ भू॒तस्य॒ भव्य॑स्य॒ पत्न्यु॒रुं लो॒कं पृ॑थि॒वी नः॑ कृणोतु॥१॥",
    transliteration: "satyaṃ bṛhad ṛtam ugraṃ dīkṣā tapo brahma yajñaḥ pṛthivīṃ dhārayanti |\nsā no bhūtasya bhavyasya patny uruṃ lokaṃ pṛthivī naḥ kṛṇotu || 1 ||",
    hindiTranslation: "महान् सत्य, अटल प्राकृतिक व्यवस्था (ऋत), दृढ़ निष्ठा, दीक्षा, तपस्या, ब्रह्मज्ञान और परोपकारी यज्ञ—ये दिव्य मूल्य इस पृथ्वी को धारण किए हुए हैं। भूत और भविष्य की स्वामिनी वह माता पृथ्वी हमारे लिए विस्तृत एवं समृद्ध जीवन का मार्ग प्रशस्त करे।",
    englishTranslation: "Truth, high order (Rita), mighty dedication, consecration, austerity, spiritual knowledge, and selfless sacrifice uphold the Mother Earth. May She, the sovereign mistress of what has been and what shall be, grant us expansive freedom and prosperity.",
    hinglishTranslation: "Mahan satya, prakritik niyam (Rita), deeksha, tap, brahma-gyan aur yagya dharti ko sambhale hue hain. Bhoot aur bhavishya ki swamini yeh prithvi hamare liye kalyan kari bane.",
    padapatha: [
      { word: "स॒त्यम्", meaning: "सत्य" },
      { word: "बृ॒हत्", meaning: "महान्" },
      { word: "ऋ॒तम्", meaning: "शाश्वत प्राकृतिक नियम" },
      { word: "उ॒ग्रम्", meaning: "दृढ़/तेजस्वी" },
      { word: "दी॒क्षा", meaning: "दीक्षा" },
      { word: "तपः॑", meaning: "तपस्या" },
      { word: "ब्रह्म॑", meaning: "ज्ञान" },
      { word: "य॒ज्ञः", meaning: "यज्ञ" },
      { word: "पृ॒थि॒वीम्", meaning: "धरती को" },
      { word: "धा॒र॒य॒न्ति॒", meaning: "धारण करते हैं" }
    ],
    shastricContext: "पृथ्वी सूक्त का प्रथम उद्घाटन मंत्र। प्रकृति और मानवता के नैतिक आधार का विश्व-प्रथम संविधान।",
    orderIndex: 5,
    status: "ACTIVE"
  },
  {
    id: "av-12-1-12",
    vedaId: "atharvaveda",
    nodeId: "av-kanda-12-bhumi",
    vedaName: "अथर्ववेद (Atharvaveda)",
    shakha: "शौनक शाखा",
    textName: "अथर्ववेद संहिता (पृथ्वी / भूमि सूक्त)",
    sectionRef: "काण्ड १२, सूक्त १",
    mantraNumber: "१२.१.१२",
    rishi: "अथर्वा",
    devata: "भूमि (Mother Earth)",
    chhanda: "त्रिष्टुप्",
    svara: "सस्वर वैदिक पाठ (अथर्व स्वर)",
    sanskrit: "ॐ यत् ते॒ मध्यं॑ पृथि॒वि यच्च॒ नभ्यं॒ यास्त॑ ऊ॒र्जस्त॒न्वः॒ संब॑भू॒वुः।\nतासु॑ नो धेह्य॒भि नः॑ पवस्व मा॒ता भूमिः॑ पु॒त्रो अ॒हं पृ॑थि॒व्याः।\nप॒र्जन्यः॑ पि॒ता स उ॑ नः पिपर्तु॥१२॥",
    transliteration: "oṃ yat te madhyaṃ pṛthivi yac ca nābhyaṃ yās ta ūrjas tanvaḥ sambabhūvuḥ |\ntāsu no dhehy abhi naḥ pavasva mātā bhūmiḥ putro ahaṃ pṛthivyāḥ |\nparjanyaḥ pitā sa u naḥ pipartu || 12 ||",
    hindiTranslation: "हे पृथ्वी! जो आपका मध्य भाग है, जो आपकी नाभि है, और जो आपकी ऊर्जावान पोषक शक्तियाँ हैं, उनमें हमें स्थापित कीजिए। हमारे प्रति पवित्र बनिए। भूमि मेरी माता है और मैं पृथ्वी का पुत्र हूँ; पर्जन्य (मेघ) हमारे पिता हैं, वे हमारा पालन-पोषण करें।",
    englishTranslation: "O Earth, that which is your center, that which is your navel, and all those nourishing energies that have manifested in you—place us within them and purify us. The Earth is my Mother, and I am the son of the Earth; rain (Parjanya) is our father, may he nourish us.",
    hinglishTranslation: "Hey Dharti Mata! Jo aapka madhya hai, aapki naabhi hai aur poshak urja hai, usme hume sthapit karein. Dharti meri Mata hai aur main is Prithvi ka putra hoon. Megh hamare pita hain jo hamara palan karein.",
    padapatha: [
      { word: "यत्", meaning: "जो" },
      { word: "ते॒", meaning: "तेरा" },
      { word: "मध्य॑म्", meaning: "मध्य भाग" },
      { word: "पृ॒थि॒वि॒", meaning: "हे पृथ्वी" },
      { word: "यत्", meaning: "जो" },
      { word: "च॒", meaning: "और" },
      { word: "नाभ्य॑म्", meaning: "नाभि/केंद्र" },
      { word: "ऊ॒र्जः", meaning: "ऊर्जाएँ" },
      { word: "मा॒ता", meaning: "माता" },
      { word: "भूमिः॑", meaning: "भूमि" },
      { word: "पु॒त्रः", meaning: "पुत्र" },
      { word: "अ॒हम्", meaning: "मैं" },
      { word: "पृ॒थि॒व्याः॑", meaning: "पृथ्वी का" },
      { word: "प॒र्जन्यः॑", meaning: "मेघ/वर्षा" },
      { word: "पि॒ता", meaning: "पिता" }
    ],
    shastricContext: "वैदिक राष्ट्रप्रेम और पर्यावरण-चेतना का अमर घोष: 'माता भूमिः पुत्रोऽहं पृथिव्याः'। मानव और प्रकृति के मातृवत सम्बन्ध का चरम साक्ष्य।",
    orderIndex: 6,
    status: "ACTIVE"
  },
  {
    id: "av-19-9-14",
    vedaId: "atharvaveda",
    nodeId: "av-kanda-19-shanti",
    vedaName: "अथर्ववेद (Atharvaveda)",
    shakha: "शौनक शाखा",
    textName: "अथर्ववेद संहिता (विश्व शान्ति सूक्त)",
    sectionRef: "काण्ड १९, सूक्त ९",
    mantraNumber: "१९.९.१४",
    rishi: "अथर्वा",
    devata: "विश्व शान्ति / सर्वदेव",
    chhanda: "अतिजगती (५२ वर्ण)",
    svara: "सस्वर वैदिक पाठ (अथर्व स्वर)",
    sanskrit: "ॐ द्यौः शान्तिरन्तरिक्षं शान्तिः पृथिवी शान्तिरापः शान्तिरोषधयः शान्तिः।\nवनस्पतयः शान्तिर्विश्वे देवाः शान्तिर्ब्रह्म शान्तिः सर्वं शान्तिः शान्तिरेव शान्तिः सा मा शान्तिरेधि॥१४॥",
    transliteration: "oṃ dyauḥ śāntir antarikṣaṃ śāntiḥ pṛthivī śāntir āpaḥ śāntir oṣadhayaḥ śāntiḥ |\nvanaspatayaḥ śāntir viśve devāḥ śāntir brahma śāntiḥ sarvaṃ śāntiḥ śāntir eva śāntiḥ sā mā śāntir edhi || 14 ||",
    hindiTranslation: "द्युलोक शांत हो, अंतरिक्ष शांत हो, पृथ्वी शांत हो, जल शांत हो, ओषधियाँ शांत हों, वनस्पतियाँ शांत हों, समस्त देवगण शांत हों, ब्रह्म शांत हो, सब कुछ शांत हो; केवल शांति ही शांति व्याप्त हो, और वह परम शांति मुझे प्राप्त हो।",
    englishTranslation: "May there be peace in heaven, peace in intermediate space, peace on earth, peace in waters, peace in plants, peace in trees, peace in all gods, peace in Brahman, peace in all, peace alone peace, may that peace come to me.",
    hinglishTranslation: "Swarg me shanti ho, antariksh me shanti ho, dharti me shanti ho, jal aur aushadhi me shanti ho, ped paudho me shanti ho, sabhi me shanti ho aur wah shanti mujhe mile.",
    padapatha: [
      { word: "द्यौः", meaning: "स्वर्ग" },
      { word: "शान्तिः", meaning: "शांत हो" },
      { word: "अन्तरिक्षम्", meaning: "अंतरिक्ष" },
      { word: "पृथिवी", meaning: "पृथ्वी" },
      { word: "आपः", meaning: "जल" },
      { word: "ओषधयः", meaning: "औषधियाँ" },
      { word: "वनस्पतयः", meaning: "वृक्ष" },
      { word: "विश्वे", meaning: "समस्त" },
      { word: "देवाः", meaning: "देवगण" },
      { word: "ब्रह्म", meaning: "परमात्मा" },
      { word: "सर्वम्", meaning: "सब कुछ" },
      { word: "शान्तिः", meaning: "शांति" }
    ],
    shastricContext: "अथर्ववेद का विश्व-कल्याणकारी शान्ति मंत्र। समस्त सृष्टि में सामंजस्य स्थापित करने की वैदिक प्रार्थना।",
    orderIndex: 14,
    status: "ACTIVE"
  }
];

// Write backend dataset
const backendPath = path.join(__dirname, "src/modules/library/data/initialVedicHeritageData.js");
const backendContent = `/**
 * Comprehensive Authentic Vedic Heritage Dataset
 * Sourced directly from the Government of India's Vedic Heritage Portal (vedicheritage.gov.in)
 * Covering all 4 Vedas: Rigveda, Yajurveda, Samaveda, and Atharvaveda
 */

export const INITIAL_VEDAS = ${JSON.stringify(VEDAS, null, 2)};

export const INITIAL_VEDA_NODES = ${JSON.stringify(NODES, null, 2)};

export const INITIAL_VEDA_MANTRAS = ${JSON.stringify(MANTRAS, null, 2)};

module.exports = {
  INITIAL_VEDAS,
  INITIAL_VEDA_NODES,
  INITIAL_VEDA_MANTRAS,
};
`;

fs.writeFileSync(backendPath, backendContent, "utf-8");
console.log("Wrote backend initialVedicHeritageData.js successfully!");
console.log(`Vedas: ${VEDAS.length}, Nodes: ${NODES.length}, Mantras: ${MANTRAS.length}`);

// Write frontend veda-library datasets
const vedaLibDataDir = path.resolve(__dirname, "../../veda-library/src/data");
if (fs.existsSync(vedaLibDataDir)) {
  const frontendMantraFile = path.join(vedaLibDataDir, "vedicMantrasData.js");
  const frontendContent = `/**
 * Authentic Vedic Mantras Dataset
 * Sourced from the Government of India's Vedic Heritage Portal (vedicheritage.gov.in)
 * 3-Language translations (Hindi, English, Hinglish) & Padapatha
 */

export const ALL_VEDIC_MANTRAS = ${JSON.stringify(MANTRAS, null, 2)};

export const VEDIC_MANTRAS = {};
ALL_VEDIC_MANTRAS.forEach((m) => {
  VEDIC_MANTRAS[m.id] = m;
});

export function getMantraById(id) {
  return VEDIC_MANTRAS[id] || ALL_VEDIC_MANTRAS.find((m) => m.id === id) || null;
}

export function getMantrasByVeda(vedaId) {
  return ALL_VEDIC_MANTRAS.filter((m) => m.vedaId === vedaId);
}

export function getMantrasByNode(nodeId) {
  return ALL_VEDIC_MANTRAS.filter((m) => m.nodeId === nodeId);
}

export default VEDIC_MANTRAS;
`;
  fs.writeFileSync(frontendMantraFile, frontendContent, "utf-8");
  console.log("Wrote veda-library/src/data/vedicMantrasData.js successfully!");
}
