import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CalendarDays, Check, Clock3, Languages, MessageCircle, Phone, ShieldCheck, Sparkles, Star, Users, Video } from "lucide-react";
import { getAstrologerBySlug } from "../data/astrologers";
import { useToast } from "../../../components/ui/toastContext";

const durations = [10, 15, 30, 45, 60];
const dates = [{ key: "today", label: "Today" }, { key: "tomorrow", label: "Tomorrow" }, { key: "next", label: "Next available" }];
const typeDetails = { "Audio Call": [Phone, "One-to-one voice consultation"], Chat: [MessageCircle, "Private text consultation"], "Video Call": [Video, "Face-to-face guidance"] };
export const calculateTotal = (rate, duration) => rate * duration;

const AstrologerDetails = () => {
  const { slug } = useParams();
  const astrologer = getAstrologerBySlug(slug);
  const { showToast } = useToast();
  const [consultationType, setConsultationType] = useState(astrologer?.consultationTypes?.[0] || "Audio Call");
  const [duration, setDuration] = useState(15);
  const [selectedDate, setSelectedDate] = useState(astrologer?.availableSlots.today?.length ? "today" : "tomorrow");
  const [selectedSlot, setSelectedSlot] = useState("");
  const slots = useMemo(() => astrologer?.availableSlots[selectedDate] || [], [astrologer, selectedDate]);
  const total = astrologer ? calculateTotal(astrologer.pricePerMinute, duration) : 0;
  const dateLabel = dates.find((item) => item.key === selectedDate)?.label;

  if (!astrologer) return <section className="min-h-[65vh] bg-[#fffaf0] px-5 py-16"><div className="mx-auto max-w-[680px] rounded-[24px] border border-[#e4cd9d] bg-[#fffdf9] p-10 text-center"><Sparkles className="mx-auto text-[#d49a25]" /><h1 className="mt-4 font-serif text-[38px]">Astrologer not found</h1><p className="mt-3 text-[14px] leading-6 text-[#75695c]">This profile may no longer be available. Browse our verified astrologers to find the right guide.</p><Link to="/astrologers" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#eab12c] px-5 py-3 text-[12px] font-semibold"><ArrowLeft size={15} />Back to astrologers</Link></div></section>;

  const selectDate = (date) => { setSelectedDate(date); setSelectedSlot(""); };
  const continueBooking = () => selectedSlot ? showToast("Your consultation request has been prepared. Booking confirmation will be available soon.") : showToast("Please select a preferred time slot to continue.", "error");

  return (
    <section className="min-h-screen bg-[#fffaf0] px-5 py-10 sm:px-8 lg:px-12">
      <div className="mx-auto max-w-[1240px]">
        <Link to="/astrologers" className="inline-flex items-center gap-2 text-[12px] font-semibold text-[#6d5b45] transition hover:text-[#b36c1e]"><ArrowLeft size={16} />Back to astrologers</Link>
        <div className="mt-6 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_370px] xl:grid-cols-[minmax(0,1fr)_400px]">
          <div className="space-y-7">
            <article className="rounded-[25px] border border-[#e3ca97] bg-[#fffdf9] p-5 shadow-[0_15px_35px_rgba(80,60,30,0.05)] sm:p-7">
              <div className="flex flex-col gap-5 sm:flex-row">
                <div className="relative h-[130px] w-[130px] shrink-0 overflow-hidden rounded-[22px] border border-[#e1c995] bg-[#f8e7c2]"><img src={astrologer.image} alt={astrologer.name} className="h-full w-full object-cover" onError={(event) => { event.currentTarget.style.display = "none"; }} /><span className={`absolute bottom-3 left-3 rounded-full border border-white/70 px-2.5 py-1 text-[10px] font-semibold ${astrologer.online ? "bg-[#eaf0df] text-[#60783e]" : "bg-[#f3ede4] text-[#75695c]"}`}>{astrologer.online ? "● Available now" : "● Offline"}</span></div>
                <div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#b36c1e]">Verified astrologer</p><h1 className="mt-2 font-serif text-[37px] leading-none text-[#2b241d] sm:text-[44px]">{astrologer.name}</h1><p className="mt-2 text-[14px] text-[#75695c]">{astrologer.title}</p></div><span className="flex items-center gap-1 rounded-full bg-[#fbefd9] px-3 py-1.5 text-[12px] font-semibold text-[#725a25]"><Star size={14} fill="#eab12c" className="text-[#eab12c]" />{astrologer.rating} <span className="font-normal text-[#75695c]">({astrologer.reviews})</span></span></div><div className="mt-5 grid gap-3 text-[12px] text-[#685c50] sm:grid-cols-3"><span className="flex items-center gap-2"><Clock3 size={15} className="text-[#c88918]" />{astrologer.experience}+ years</span><span className="flex items-center gap-2"><Languages size={15} className="text-[#c88918]" />{astrologer.languages.join(", ")}</span><span className="flex items-center gap-2"><Users size={15} className="text-[#c88918]" />{astrologer.sessions} sessions</span></div></div>
              </div>
              <div className="mt-6 border-t border-[#eee1ca] pt-5"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#75695c]">Expertise</p><div className="mt-3 flex flex-wrap gap-2">{astrologer.expertise.map((item) => <span key={item} className="rounded-full border border-[#ead7af] bg-[#fffaf0] px-3 py-1.5 text-[11px] text-[#725a25]">{item}</span>)}</div></div>
            </article>
            <article className="rounded-[23px] border border-[#e3ca97] bg-[#fffdf9] p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#ef6c1f]">About</p><h2 className="mt-2 font-serif text-[32px]">About the Astrologer</h2><p className="mt-4 text-[14px] leading-7 text-[#675b50]">{astrologer.about}</p><h3 className="mt-7 font-serif text-[25px]">Areas of Expertise</h3><div className="mt-3 flex flex-wrap gap-2">{astrologer.specializations.map((item) => <span key={item} className="rounded-full bg-[#fbefd9] px-3 py-1.5 text-[11px] text-[#725a25]">{item}</span>)}</div></article>
            <article className="rounded-[23px] border border-[#e3ca97] bg-[#f9efd9] p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#b36c1e]">A considered experience</p><h2 className="mt-2 font-serif text-[31px]">Why consult with this expert?</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Experienced practitioner", "Personalized guidance", "Private & confidential consultation", "Trusted by thousands of seekers"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-[#e5d2aa] bg-[#fffaf0] px-4 py-3 text-[12px] font-medium text-[#5f5143]"><ShieldCheck size={17} className="shrink-0 text-[#b58225]" />{item}</div>)}</div></article>
          </div>
          <aside className="lg:sticky lg:top-24"><div className="rounded-[24px] border border-[#dfc58d] bg-[#fffdf9] p-5 shadow-[0_18px_45px_rgba(80,60,30,0.09)] sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#ef6c1f]">Personal consultation</p><h2 className="mt-2 font-serif text-[31px]">Choose how to connect</h2><div className="mt-5 grid gap-2">{astrologer.consultationTypes.map((type) => { const [Icon, description] = typeDetails[type]; const selected = consultationType === type; return (<button type="button" key={type} onClick={() => setConsultationType(type)} className={`flex items-center gap-3 rounded-xl border p-3.5 text-left transition focus-visible:ring-2 focus-visible:ring-[#c88918] ${selected ? "border-[#c88918] bg-[#fff3d7]" : "border-[#e6d7bc] hover:border-[#d6a13b]"}`}><span className={`grid h-9 w-9 place-items-center rounded-full ${selected ? "bg-[#eab12c]" : "bg-[#fbefd9]"}`}><Icon size={17} /></span><span className="flex-1"><span className="block text-[12px] font-semibold">{type}</span><span className="mt-0.5 block text-[10px] text-[#75695c]">{description}</span></span>{selected && <Check size={17} className="text-[#a36c0c]" />}</button>); })}</div>
            <div className="mt-6 border-t border-[#eee1ca] pt-5"><h3 className="font-serif text-[24px]">Choose consultation duration</h3><div className="mt-3 grid grid-cols-3 gap-2">{durations.map((item) => <button type="button" key={item} onClick={() => setDuration(item)} className={`rounded-lg border px-2 py-2.5 text-[11px] font-semibold transition ${duration === item ? "border-[#c88918] bg-[#eab12c]" : "border-[#e6d7bc] hover:border-[#d6a13b]"}`}>{item} min</button>)}</div></div>
            <div className="mt-6 border-t border-[#eee1ca] pt-5"><h3 className="font-serif text-[24px]">Choose your preferred time</h3><div className="mt-3 grid grid-cols-3 gap-1.5">{dates.map((date) => <button type="button" key={date.key} onClick={() => selectDate(date.key)} className={`rounded-lg border px-2 py-2 text-[10px] font-semibold ${selectedDate === date.key ? "border-[#c88918] bg-[#fff3d7] text-[#785313]" : "border-[#e6d7bc] text-[#75695c]"}`}>{date.label}</button>)}</div><div className="mt-3 grid grid-cols-3 gap-2">{slots.length ? slots.map((slot) => { const unavailable = astrologer.unavailableSlots.includes(slot); const selected = selectedSlot === slot; return <button type="button" disabled={unavailable} key={slot} onClick={() => setSelectedSlot(slot)} className={`rounded-lg border px-1 py-2 text-[10px] font-semibold transition ${unavailable ? "cursor-not-allowed border-[#eee5d7] bg-[#f7f4ef] text-[#b4aa9d] line-through" : selected ? "border-[#c88918] bg-[#eab12c] text-[#2b241d]" : "border-[#e6d7bc] text-[#5f554a] hover:border-[#d6a13b]"}`}>{slot}</button>; }) : <p className="col-span-3 rounded-lg bg-[#faf3e4] p-3 text-center text-[11px] text-[#75695c]">No slots are available for this day. Please choose another date.</p>}</div></div>
            <div className="mt-6 rounded-[16px] border border-[#e7d7b7] bg-[#faf3e4] p-4"><h3 className="font-serif text-[23px]">Consultation Summary</h3><dl className="mt-3 space-y-2 text-[11px]"><div className="flex justify-between gap-4"><dt className="text-[#75695c]">Astrologer</dt><dd className="text-right font-semibold">{astrologer.name}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#75695c]">Consultation</dt><dd className="font-semibold">{consultationType}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#75695c]">Duration</dt><dd className="font-semibold">{duration} minutes</dd></div><div className="flex justify-between gap-4"><dt className="text-[#75695c]">Date & time</dt><dd className="text-right font-semibold">{selectedSlot ? `${dateLabel}, ${selectedSlot}` : "Select a slot"}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#75695c]">Rate</dt><dd className="font-semibold">{astrologer.currency}{astrologer.pricePerMinute}/min</dd></div></dl><div className="mt-4 flex items-end justify-between border-t border-[#e3cfaa] pt-3"><span className="text-[12px] font-semibold">Estimated total</span><span className="font-serif text-[28px]">{astrologer.currency}{total}</span></div></div>
            <button type="button" onClick={continueBooking} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#eab12c] py-3.5 text-[13px] font-semibold text-[#2b241d] shadow-[0_8px_18px_rgba(190,145,50,0.18)] transition hover:bg-[#dca522]">Continue <CalendarDays size={16} /></button><p className="mt-3 text-center text-[10px] leading-4 text-[#8b7e70]">No payment is required yet. You will be able to review your request before confirmation.</p>
          </div></aside>
        </div>
      </div>
    </section>
  );
};

export default AstrologerDetails;
